week: 27
vol_num: 27
periodo: "6 – 12 jul 2026"
mes_año: "Julio 2026"
fecha_pub: "LUNES 07 de Julio de 2026"
week_prev: 26
vol_num_prev: 26
periodo_prev: "29 jun – 05 jul 2026"
paths:
  project: "C:/Users/federico.iglesias/Price_stage"
  outputs: "C:/Users/federico.iglesias/Price_stage"
  uploads: "C:/Users/federico.iglesias/Price_stage"
