# dest_mapping.py — generado automáticamente por auto_mapper.py
# Hoteles mapeados por nombre/keyword + búsqueda web para los ambiguos.
# Editar para correcciones o agregar hoteles faltantes.

DEST_MAPPING = {
    '12HEH Pattaya': 'Pattaya',
    '19 Belo Cabana': 'Goa',
    '7 Days Premium Hotel Pattaya': 'Pattaya',
    '8fold-Pinecrest By LaRiSa, Bhimtal': 'Bhimtal',
    '9h nine hours Sendai': 'Sendai',
    '@HOME by Best Western St. George': 'St. George',
    'A.A. Pattaya Golden Beach Hotel': 'Pattaya',
    'AOIKE Hot Spring Hotel': 'Yilan',
    'APA Hotel TKP Sendai-Ekikita': 'Sendai',
    'ASPEN HOTEL ÇANAKKALE': 'Canakkale',
    'Aangan Royal Stay - Your Mountain Home in Dharamshala': 'Dharamshala',
    'Aaroham By Aamod Dharamshala': 'Dharamshala',
    'Abani Jomtien Inn': 'Pattaya',
    'Acanti Dharamshala': 'Dharamshala',
    'Adiwana Dara Ayu': 'Bali',
    'Adriatic Palace Hotel Pattaya': 'Pattaya',
    'Aires Serranos - Suites': 'Córdoba',
    'Aitken Hill': 'Melbourne',
    'Akara Hotel Pattaya': 'Pattaya',
    'Akira Pattaya': 'Pattaya',
    'Alam Jogja Resort': 'Yogyakarta',
    'Alamanda Lovina Resort': 'Bali',
    'Alassari Plantation': 'Bali',
    'All-Ur Boutique Motel - Hua-Lian Branch': 'Hualien',
    'All-Ur Boutique Motel - Yi-Lan Branch': 'Yilan',
    'Almont Hotel Sendai': 'Sendai',
    'Alta Gracia Parque Hotel': 'Alta Gracia',
    'Amanti Hotel Seoul': 'Seoul',
    'Amaranta Prambanan Yogyakarta': 'Yogyakarta',
    'Amethyst Hotel Pattaya': 'Pattaya',
    'Amiigo Kohlarn': 'Pattaya',
    'An Lam Retreats Ninh Van Bay': 'Nha Trang',
    'Anandam - A Luxury resort in Udaipur': 'Udaipur',
    'Anantra Resort Pattaya': 'Pattaya',
    'Andeluna Winery Lodge': 'Mendoza',
    'Andores Resort And Spa': 'Goa',
    'Angels Inn Jiaoxi Hotspring': 'Yilan',
    'Anook Hotel Suwon Ingye': 'Suwon',
    'Anook Ryokan and Anook Air Cheongju': 'Cheongju',
    'Ansan Hotel 727': 'Ansan',
    'Ansan Hotel Wol': 'Ansan',
    'Ansan Queens Hotel': 'Ansan',
    'Ansan Rosa Bell Hotel': 'Ansan',
    'Ansan Seowon Hotel': 'Ansan',
    'Anshan Hotel BIZ': 'Ansan',
    'Anshan Hotel Sense': 'Ansan',
    'Anvaya Udaipur - Steps from Lake Pichola, Old City': 'Udaipur',
    'Aotel Pangot (Formerly Royal Cliff)': 'Pattaya',
    'Apart Hotel La Bora': 'Argentina',
    'Aravali Marriott Resort & Spa, Delhi NCR': 'Nueva Delhi',
    'Arawana Express North Pattaya': 'Pattaya',
    'Arawana Regency North Pattaya': 'Pattaya',
    'Arawana Regency South Pattaya': 'Pattaya',
    'Arbour Hotel And Residence Pattaya': 'Pattaya',
    'Archontiko Galliaki in Crete': 'Creta',
    'Ardency Inn by Park Tree Udaipur': 'Udaipur',
    'Argo Pattaya Resort and Villas': 'Pattaya',
    'Aruvi Resort Munnar': 'Munnar',
    'Aryston Hotel Udaipur': 'Udaipur',
    'Ascent Premiere Pasuruan': 'Surabaya',
    'Aswan Cozy Apartment.': 'Aswan',
    'At Inn Hotel Toyotashi station': 'Toyota',
    'At Sea Hotel Pattaya': 'Pattaya',
    'Atlantis Condo and Water Park Pattaya by the Sea': 'Pattaya',
    'Atman Resort Dharamshala By Leisure Hotels': 'Dharamshala',
    'Atthebeach Kohlarn': 'Pattaya',
    'Atulya Niwas, Udaipur': 'Udaipur',
    'Aurika, Udaipur - Luxury by Lemon Tree Hotels': 'Udaipur',
    'AutoCamp Zion': 'Zion',
    'Avadale Munnar - Stag Groups Not Allowed': 'Munnar',
    'Avana Hotel Pemuteran': 'Bali',
    'Avexia Elite Resort & Spa Udaipur': 'Udaipur',
    'Azzure By Spree Goa': 'Goa',
    'B&B Hotel Wolfsburg-Weyhausen': 'Wolfsburg',
    'B&B PIEDICASTELLO': 'Trento',
    'B2 Hotel South Pattaya Premier Hotel': 'Pattaya',
    'BIG4 Frankston Holiday Park': 'Melbourne',
    'BON Hotel Rustenburg': 'Rustenburg',
    'Baan Coconut At Koh Larn': 'Pattaya',
    'Baan I Taley On Sea': 'Pattaya',
    'Baan Pattaya by Sabai': 'Pattaya',
    'Baan Talay': 'Pattaya',
    'Babylon Residence Inn pattaya': 'Pattaya',
    'Bagus Homestay Pemuteran': 'Bali',
    'Bali Menjangan Boutique Villas': 'Bali',
    'Bali au Naturel - Adults Only': 'Bali',
    'BaliTrekk Boutique Hotel': 'Bali',
    'Bamboo Saa Resort & Spa - Udaipur': 'Udaipur',
    'Banana Guesthouse South Pattaya': 'Pattaya',
    'Beachwalk Jomtien': 'Pattaya',
    'Bear Creek Guest Ranch': 'Montana',
    'Beargrass Lodging and RV Resort': 'Montana',
    'Bears Den Pattaya': 'Pattaya',
    'Beauty Garden Hotel Jiaoxi': 'Yilan',
    'Belvilla Ananda Resort Lovina BeachNearPantai Lovina': 'Bali',
    'Belvilla Calm Haven Amabela Garden Lovina BeachNearLovina Beach': 'Bali',
    'Benada Piyungan Yogyakarta by ABM': 'Yogyakarta',
    'Bensri Residence Pattaya': 'Pattaya',
    'Best Western Ebbw Vale': 'Gales',
    'Best Western Plus Coachella Valley Inn & Suites': 'Coachella Valley',
    'Beston Pattaya': 'Pattaya',
    'Bhanwar Singh Palace Pattaya': 'Pattaya',
    'Bhraj Inn Hotel Udaipur': 'Udaipur',
    'Biorock Homestay': 'Bali',
    'Birds and Bees Resort': 'Pattaya',
    'Bkl Pool Villa Pattaya': 'Pattaya',
    'Blanc Hotel Cheongju': 'Cheongju',
    'Bloom Boutique | Lake Pichola': 'Udaipur',
    'BloomSuites Calangute': 'Goa',
    'Blue Bed Pattaya SHA by Zuzu': 'Pattaya',
    'Blue Garden Resort Pattaya': 'Pattaya',
    'Bondalem Beach Club': 'Bali',
    'Boulevard Munnar': 'Munnar',
    'Boutique City And Bravo Hotel Pattaya': 'Pattaya',
    'Brahma Niwas - Best Lake View Hotel in Udaipur': 'Udaipur',
    'Breezy Pattaya': 'Pattaya',
    'Brighton Grand Hotel Pattaya': 'Pattaya',
    'Brij Atmanya, Bhowali | A Luxury Mountain Escape': 'Nainital',
    'British Hotel Girne': 'Chipre',
    'Bucheon A Hotel': 'Bucheon',
    'Bucheon Hotel Ben': 'Bucheon',
    'Budget Motel Granite City/St Louis Area': 'St. Louis',
    'Buubble Hotel - Hrosshagi': 'Islandia',
    'By Dee @Jomtien': 'Pattaya',
    'CK Resort Pattaya': 'Pattaya',
    'COSI Pattaya Wong Amat Beach': 'Pattaya',
    'CU at Jomtien': 'Pattaya',
    'Cabinas Arenal Home': 'Arenal',
    'Cancun Sokhna Resort & Villas': 'Ain Sokhna',
    'Cape Montenegro Villas': 'Montenegro',
    "Casa Palmera by Avantstay Entertainer's Oasis w/ Guesthouse": 'Coachella Valley',
    'Castle Oodeypore A Boutique Stay Udaipur': 'Udaipur',
    'Caviar Kohlarn': 'Pattaya',
    'Center Hotel Toyota': 'Toyota',
    'Centre Point Prime Hotel Pattaya': 'Pattaya',
    'Chandralok - A Boutique Hotel in Udaipur Near Fateh Sagar Lake': 'Udaipur',
    'Charinn Kohlarn': 'Pattaya',
    'Charm Hostel at Jomtien': 'Pattaya',
    'Check-in Resort Koh Larn': 'Pattaya',
    'Cheongju Hotel Dictionary': 'Cheongju',
    'Cheongju Maryjane Hotel': 'Cheongju',
    'Cherry Valley Manor Luxury Bed and Breakfast': 'Pocono Mountains',
    'Chezzotel Pattaya': 'Pattaya',
    'Chirping Hills Resort Bhimtal': 'Bhimtal',
    'Churana Resort Motobu': 'Okinawa',
    'Citrus Grande Hotel Pattaya by Compass Hospitality': 'Pattaya',
    'Clarks Inn Express Udaipur': 'Udaipur',
    'Classic Lodges Ramsey Park': 'Isle of Man',
    'Click Collection The Abode Dharamshala': 'Dharamshala',
    'Climax Berlin': 'Berlin',
    'Cloudotel Walking Street Pattaya': 'Pattaya',
    'Coco Beach Hotel Jomtien Pattaya': 'Pattaya',
    'Commodious Hotel Kupang': 'Kupang',
    'Coral Sea Beach & Aqua Park': 'Hurghada',
    'County Homes Munnar': 'Munnar',
    'Courtyard Seoul Botanic Park': 'Seoul',
    'Crocodile Kruger Safari Lodge': 'Kruger',
    'Cross Pattaya Pratamnak': 'Pattaya',
    "D'Charruas Cabañas Chajari": 'Chajarí',
    "D'Polo Club And Spa Resort, Dharamshala": 'Dharamshala',
    'DEL MAX resort Pattaya': 'Pattaya',
    'DUPLICADO Alassari Plantation': 'Bali',
    'DUPLICADO Ardency Inn by Park Tree Udaipur': 'Udaipur',
    'DUPLICADO Club Mahindra Munnar': 'Munnar',
    'DUPLICADO Fiesto Hotel and Suites Enugu': 'Enugu',
    'DUPLICADO Goroomgo Silver Tree inn Bhimtal': 'Bhimtal',
    'DUPLICADO Hotel Les Champs Jiaosi': 'Yilan',
    'DUPLICADO Kruger Maroela Lodge': 'Kruger',
    'DUPLICADO Modessa Island': 'Mindoro',
    'DUPLICADO Palace Inn Toyota': 'Toyota',
    'DUPLICADO ProfilHotels Halmstad Plaza': 'Halmstad',
    'DUPLICADO Radisson Udaipur': 'Udaipur',
    'DUPLICADO Raffles Udaipur': 'Udaipur',
    'DUPLICADO Royal Cliff Beach Terrace Hotel Pattaya': 'Pattaya',
    'DUPLICADO Sayaji Resort and Spa Udaipur': 'Udaipur',
    'DUPLICADO Scenic, Munnar - IHCL SeleQtions': 'Munnar',
    'DUPLICADO The Leela Palace Udaipur': 'Udaipur',
    'DUPLICADO The Proud Hotel Pattaya': 'Pattaya',
    'DUPLICADO Toyota Prestige Hotel': 'Toyota',
    'DUPLICADO Tree of Life Amara Resorts & Spa Udaipur': 'Udaipur',
    'DUPLICADO Villa Oranje Pattaya': 'Pattaya',
    'DUPLICADO Zubani hotel and suites': 'Enugu',
    'DUPLICADO-Quality Inn Williston Area': 'North Dakota',
    'Daiwa Roynet Hotel Sendai-nishiguchi PREMIER': 'Sendai',
    'DaiwaRoynetHotel Sendai Ichibanchou PREMIER': 'Sendai',
    'Daksh The Fateh Retreat - Udaipur': 'Udaipur',
    'Darling Harbour Residence - Pattaya': 'Pattaya',
    'Days Inn by Wyndham Perrysburg/Toledo': 'Toledo',
    'DeeProm Pattaya Hotel': 'Pattaya',
    'Deep Blue Z10 Pattaya': 'Pattaya',
    'Dera Pichola A Lake Facing Hotel': 'Udaipur',
    'Desert Escape with Pool, Firepit, Putting Green': 'Coachella Valley',
    'Devi Palace Monsoon Palace View Resort Udaipur': 'Udaipur',
    'Dockside Guest Quarters & Restaurant': 'Maine',
    'Dolomia rosmini': 'Trento',
    'Dormy Inn Express Sendai Seaside': 'Sendai',
    'Dormy Inn Seoul Gangnam': 'Seoul',
    'Doubletree By Hilton Canakkale': 'Canakkale',
    'Dragon Beach Resort Jomtien Pattaya': 'Pattaya',
    'Dream Catcher Plantation Resort': 'Bali',
    'Dreams Resort Udaipur': 'Udaipur',
    'EEC Home North Pattaya - Naklua': 'Pattaya',
    'ENTRE VIÑEDOS RESORT HOTEL': 'Mendoza',
    'Echor Mandara Tree Villa Dharamshala': 'Dharamshala',
    'Eco Nubia Ecolodge': 'Aswan',
    'Elgalala Aqua Park': 'Ain Sokhna',
    'Essentia Udaipur Luxury Resort & Spa': 'Udaipur',
    'Eve Place Pattaya': 'Pattaya',
    'Everhome Suites Corona': 'Los Angeles (and vicinity), CA, US',
    'Everyday Hot Spring Hotel': 'Yilan',
    'Excel Hotels & Resorts Bhimtal': 'Bhimtal',
    'Extended Stay Brunswick': 'Brunswick',
    'FX Hotel Pattaya': 'Pattaya',
    'Fairfield Inn & Suites by Marriott San Jose North/Silicon Valley': 'San Jose - Silicon Valley',
    'Fairfield by Marriott Goa Anjuna': 'Goa',
    'Fairmont Udaipur Palace': 'Udaipur',
    'Fairtex Express': 'Pattaya',
    'Fairtex Residence': 'Pattaya',
    'Fan Sea Resort Kohlarn': 'Pattaya',
    'Fiesto Continental Hotel Enugu': 'Enugu',
    'Fiesto Hotel and Suites Enugu': 'Enugu',
    'First Camp Tylösand': 'Halmstad',
    'Four Points by Sheraton Seoul, Guro': 'Seoul',
    'Fourium Pattaya Hotel and Serviced Residence': 'Pattaya',
    "Foxy Crocodile Bush Lodge & Kruger Safari's - No Loadshedding": 'Kruger',
    'Foxy Crocodile Bush Lodge & Kruger Safaris': 'Kruger',
    'Fresh Resort Pattaya': 'Pattaya',
    'GLOUCESTER HOTEL CHEONGJU': 'Cheongju',
    'Garner Hotel Pattaya Central by IHG': 'Pattaya',
    'Garrya Bianti Yogyakarta': 'Yogyakarta',
    "Genie's Pattaya": 'Pattaya',
    'Ginger Udaipur Shastri Circle': 'Udaipur',
    'Go2bed Pattaya': 'Pattaya',
    'Golden Jomtien Beach Hotel': 'Pattaya',
    'Golden Star Pattaya': 'Pattaya',
    'Golden Tulip Pattaya Beach Resort': 'Pattaya',
    'Goroomgo Adhya Inn Bhimtal': 'Bhimtal',
    'Goroomgo Agnija Udaipur': 'Udaipur',
    'Goroomgo Anant Vilas Resort Bhimtal': 'Bhimtal',
    'Goroomgo Herb Club Homestay Bhimtal': 'Bhimtal',
    'Goroomgo Hotel Hill View Homes Bhimtal': 'Bhimtal',
    'Goroomgo Kanara Bhimtal': 'Bhimtal',
    'Goroomgo Lalghat Haveli Udaipur': 'Udaipur',
    'Goroomgo Morning Moon Bhimtal': 'Bhimtal',
    'Goroomgo Palm Bhimtal': 'Bhimtal',
    'Goroomgo Portola Hotel By Parkside Dharamshala': 'Dharamshala',
    'Goroomgo Rajpal Palace Udaipur': 'Udaipur',
    'Goroomgo Rani Palace Udaipur': 'Udaipur',
    'Goroomgo Sapphire Inn Bhimtal': 'Bhimtal',
    'Goroomgo Silver Tree inn Bhimtal': 'Bhimtal',
    'Grand Allevia Villa': 'Bali',
    'Grand Continent- A Luxury Collection Udaipur': 'Udaipur',
    'Grand Hotel Prius - Adults Only': 'Pattaya',
    'Grand Kruger Lodge and Spa': 'Kruger',
    'Grand Residence Jomtien': 'Pattaya',
    'Grande Centre Point Pattaya': 'Pattaya',
    'Grande Centre Point Space Pattaya': 'Pattaya',
    'Grande Classic Pattaya': 'Pattaya',
    'Grant Village - Inside the Park': 'Yellowstone',
    'Green Forest Villa': 'Bali',
    'Griya Godean Syariah Yogyakarta': 'Yogyakarta',
    'H Avenue Hotel Idae Sinchon': 'Seoul',
    'HOTEL ALPE BELLARIA': 'Rimini',
    'HOTEL ARAWALI UDAIPUR CITY': 'Udaipur',
    'HOTEL LiVEMAX Aichi Toyota-Ekimae': 'Toyota',
    'HOTEL LiVEMAX SENDAI AOBADORI': 'Sendai',
    'HOTEL LiVEMAX SENDAI KOKUBUNCHO': 'Sendai',
    'HOUSE HOTEL Central Pattaya': 'Pattaya',
    'HOUSE HOTEL Walking Street Pattaya': 'Pattaya',
    'Halmstad Golfarena Hotell': 'Halmstad',
    'Halmstad Gårdshotell': 'Halmstad',
    'Halmstad Hotell & Vandrarhem Kaptenshamn': 'Halmstad',
    'Halo Sea Kohlarn': 'Pattaya',
    'Hamiltons Lodge And Restaurant Malelane': 'Kruger',
    'Hampton Inn & Suites Corona, Ca': 'Los Angeles (and vicinity), CA, US',
    'Happy Bou Jomtien Guesthouse': 'Pattaya',
    'Has Pattaya': 'Pattaya',
    'Heidenauer Hotel im Park': 'Dresden',
    'Henn na Hotel Premier Sendai Kokubuncho': 'Sendai',
    'Heritage Hotel Raznjevica Dvori': 'Serbia',
    'Hermann Hotel Pattaya': 'Pattaya',
    'Hide-in Udaipur': 'Udaipur',
    'Hilton Club The Beach Resort Sesoko': 'Okinawa',
    'Hilton Goa Resort Candolim': 'Goa',
    'Hilton Okinawa Sesoko Resort': 'Okinawa',
    'Himalayan Inn': 'India',
    'Historic Farmhouse in Hohnebostel With Garden Near Lake': 'Hannover',
    'Holiday Heaven Munnar': 'Munnar',
    'Holiday Inn Express & Suites Bengaluru Old Madras': 'Bengaluru',
    'Holiday Inn Express & Suites Bengaluru Old Madras Road by IHG': 'Bengaluru',
    'Holiday Inn Express Hamburg South A7 AS42 by IHG': 'Hamburg',
    'Holiday Inn Express Hongdae Seoul': 'Seoul',
    'Holiday Inn Express Langfang Yanjiao by IHG': 'Langfang',
    'Holiday Inn La Verkin Zion Park by IHG': 'Zion',
    'Homewood Suites By Hilton Fremont, Ca': 'San Jose - Silicon Valley',
    'Hosteria y Cabañas Posada Quinen by Nordic': 'Neuquén',
    'Hotal Devraj Niwas on Lake Pichola Udaipur': 'Udaipur',
    'Hotel & Spa TOPOS Sendai Station - Caters to Men': 'Sendai',
    "Hotel 360 By D'Polo Dharamshala": 'Dharamshala',
    'Hotel Alpha-One Otsu': 'Otsu',
    'Hotel Amazing Udaipur by Heritage inn': 'Udaipur',
    'Hotel Amber Pattaya': 'Pattaya',
    'Hotel Apricot One Udaipur -Near Fateh Sagar Lake': 'Udaipur',
    'Hotel Asian Plaza Dharamshala': 'Dharamshala',
    'Hotel Astor Piacenza': 'Piacenza',
    'Hotel Atlantis Otsu - Adults Only': 'Otsu',
    'Hotel Biz Suwon': 'Suwon',
    'Hotel Broadway Udaipur': 'Udaipur',
    'Hotel Calangute Central': 'Goa',
    'Hotel Cappuccino': 'Seoul',
    'Hotel City Express By Downtown Udaipur': 'Udaipur',
    'Hotel Clear Sky Udaipur': 'Udaipur',
    'Hotel Continental Relax Spa, BW Signature Collection': 'Hotel Continental Relax Spa',
    'Hotel Crown Hills Sendai Aobadori': 'Sendai',
    'Hotel Darbargarh, Udaipur': 'Udaipur',
    'Hotel Denim Seoul': 'Seoul',
    'Hotel Dharamshala Ayush Health Paradise': 'Dharamshala',
    'Hotel Dream villa udaipur': 'Udaipur',
    'Hotel Grand Bach Sendai': 'Sendai',
    'Hotel Grand Terrace Sendai Kokubuncho': 'Sendai',
    'Hotel Green Park': 'Hyderabad',
    'Hotel Green Park Udaipur': 'Hyderabad',
    'Hotel Hanuman Ghat': 'Varanasi',
    'Hotel Haridas Haveli Udaipur': 'Udaipur',
    'Hotel Harmony Blue Mcleodganj, Dharamshala': 'Dharamshala',
    'Hotel Hill view by Heritage inn Udaipur': 'Udaipur',
    'Hotel Imperial Udaipur': 'Udaipur',
    'Hotel Indigo Bali Seminyak Beach by IHG': 'Bali',
    'Hotel Isenbütteler Hof': 'Wolfsburg',
    'Hotel JK Dharamshala': 'Dharamshala',
    'Hotel Kale 17': 'Canakkale',
    'Hotel Keihan Sendai': 'Sendai',
    'Hotel Koo OotsuHyakucho': 'Otsu',
    'Hotel LaCalme Sendai - Adults Only': 'Sendai',
    'Hotel Les Champs Jiaosi': 'Yilan',
    'Hotel Livemax Sendai Hirose-dori': 'Sendai',
    'Hotel Lotus Otsu  - Adults Only': 'Otsu',
    'Hotel Luna Otsu': 'Otsu',
    'Hotel Mandovin - A Premium Hotel In Udaipur': 'Udaipur',
    'Hotel Manu Seoul': 'Seoul',
    'Hotel Manuni Inn Dharamshala': 'Dharamshala',
    'Hotel Meenakshi Udaipur': 'Udaipur',
    'Hotel Metropolitan Sendai East': 'Sendai',
    'Hotel Mewar Mahal - Udaipur': 'Udaipur',
    'Hotel Mewarts Udaipur': 'Udaipur',
    'Hotel Mirador de Barcia': 'Galicia',
    'Hotel Mumbai House Express': 'Mumbai',
    'Hotel My New Lovina': 'Bali',
    'Hotel NEO Eltari Kupang by Aston': 'Kupang',
    'Hotel Naru Seoul - MGallery Collection': 'Seoul',
    'Hotel O Hepi Bungalow Lovina': 'Bali',
    'Hotel O Near Tugu Yogyakarta 2 formerly Monjali Inn': 'Yogyakarta',
    'Hotel O Yogyakarta near MM UGM formerly Bama Guesthouse': 'Yogyakarta',
    'Hotel O near Plaza Ambarrukmo Yogyakarta formerly Wisma Arya 2': 'Yogyakarta',
    'Hotel PIN Jiaoxi': 'Yilan',
    'Hotel PORTO TARA': 'Montenegro',
    'Hotel Palace Sendai': 'Sendai',
    'Hotel Paramount Udaipur': 'Udaipur',
    'Hotel Paras Mahal': 'India',
    'Hotel Raj Kuber': 'India',
    'Hotel Ramnivas Hotel-Restaurant Udaipur': 'Udaipur',
    'Hotel Royal Palm - A Budget Hotel in Udaipur': 'Udaipur',
    'Hotel Rühen, 24 Stunden Check in, kostenfreie Parkplätze': 'Wolfsburg',
    'Hotel STIPRAM Kaliurang Yogyakarta': 'Yogyakarta',
    'Hotel Sardus Pater': 'Sardinia',
    'Hotel Shiv Sagar Haveli Udaipur': 'Udaipur',
    'Hotel Shree Khodiyar By Rangoli Udaipur': 'Udaipur',
    'Hotel Sparrow Dharamshala': 'Dharamshala',
    'Hotel Square Ansan': 'Ansan',
    "Hotel Square One By D'Polo Dharamshala  ID 92552899": 'Dharamshala',
    'Hotel Stern Pattaya': 'Pattaya',
    'Hotel Sunrise Palace Udaipur': 'Udaipur',
    'Hotel Sunshine Dharamshala': 'Dharamshala',
    'Hotel Tara Bar & Resto Air Sanih': 'Bali',
    'Hotel Townhouse @Udaipur City Railway Station': 'Udaipur',
    'Hotel Transit Pasuruan': 'Surabaya',
    'Hotel U Connect Near RTO Office, Udaipur': 'Udaipur',
    'Hotel Udai Palace': 'Udaipur',
    'Hotel Udaipur Stay': 'Udaipur',
    'Hotel Vista Sendai': 'Sendai',
    'Hotel WD': 'Seoul',
    'Hotel Yaja Cheongju Terminal Branch': 'Cheongju',
    'Hotel Yaja Suwon City Hall': 'Suwon',
    'Hotel Zlatibor': 'Serbia',
    'Hotel mountain palace Udaipur': 'Udaipur',
    'Hotel Ávila Centro': 'Ávila',
    'Hotel&Ristorante Sicilia': 'Sicilia',
    'Hotelette Seoul Station': 'Seoul',
    'Hotell Toftalund AB': 'Dinamarca',
    'House of Trento - NO Reception': 'Trento',
    'Howard Johnson by Wyndham Pattaya JC': 'Pattaya',
    'Hótel Skálholt': 'Islandia',
    'IP Plus Pool Villa Pattaya': 'Pattaya',
    'Ice Inn Hotel Pattaya': 'Pattaya',
    'Inase Otsu Machiya Bed & Breakfast': 'Otsu',
    'Incredible Stay at Water Side El Gouna': 'El Gouna',
    'Indulge Udaipur by PACK': 'Udaipur',
    'Infinity Sky 2.0 Jomtien Beach': 'Pattaya',
    'Injoy Hotel Halmstad': 'Halmstad',
    'InterContinental Pattaya Resort, an IHG Hotel': 'Pattaya',
    'Intersur Hotel La Cumbre': 'La Cumbre',
    'J Inspired Hotel Pattaya': 'Pattaya',
    'JP Inn Pattaya': 'Pattaya',
    'Jajora Udaipur By Premier Hotels': 'Udaipur',
    'Jean Boutique Pattaya': 'Pattaya',
    'Jiaoxi 320 B&B': 'Yilan',
    'Jomtien Beach Market Hotel': 'Pattaya',
    'Jomtien Beach SLEEP INN': 'Pattaya',
    'Jomtien Hisotel': 'Pattaya',
    'Jomtien Wave Residence': 'Pattaya',
    'Just Sleep Hotel Ansan Gojan Branch': 'Ansan',
    'Justa Ssatva Resort, Udaipur': 'Udaipur',
    'KJS Pattaya\u200b': 'Pattaya',
    'KKinn South Pattaya Hotel': 'Pattaya',
    'KOKO HOTEL Sendai Station South': 'Sendai',
    'KOKO HOTEL Sendai Station West': 'Sendai',
    'Kalpić Suites & Villa': 'Croacia',
    'Kangen Boutique Hotel': 'Bali',
    'Kann Pattaya Hotel': 'Pattaya',
    'Kastel Pattaya Hotel': 'Pattaya',
    'Katson Castle Dharamshala': 'Dharamshala',
    'Kavacik Asia Hotel': 'Istanbul',
    'Kavish Holiday Hill Resort': 'India',
    'Kelapa Lovina Beach Villas': 'Bali',
    'Keys Select by Lemon Tree Hotels Udaipur': 'Udaipur',
    'Koenig Hotel Pattaya': 'Pattaya',
    'Koh Larn De Beach': 'Pattaya',
    'Koh Larn FC': 'Pattaya',
    'Koh Larn Riviera': 'Pattaya',
    'Kokotel Pattaya North Beach': 'Pattaya',
    'Kotra Haveli A Boutique Hotel By The Lake Pichola': 'Udaipur',
    'Kruger Inn Backpackers': 'Kruger',
    'Kruger Maroela Lodge': 'Kruger',
    'Kruger Riverside Lodge': 'Kruger',
    'Kruger View Chalets': 'Kruger',
    'Kudrat Resort and Suites Jim Corbett': 'Jim Corbett',
    "L'Escape Hotel": 'Seoul',
    'L7 HONGDAE by LOTTE HOTELS': 'Seoul',
    'LEK Jomtien Hotel': 'Pattaya',
    'LK Celestite': 'Pattaya',
    'LK Crystal Ville Pattaya': 'Pattaya',
    'LK Majestic Villa': 'Pattaya',
    'LK President': 'Pattaya',
    'La Casa Pattaya': 'Pattaya',
    'Lafayette Boutique Hotel Yogyakarta': 'Yogyakarta',
    'Laguna House': 'Montenegro',
    'Lake Lodge Cabins - Inside the Park': 'Glacier National Park',
    'Lake McDonald Lodge - Inside the Park': 'Glacier National Park',
    'Lakeshore Hotel Suao': 'Yilan',
    'Lakeshore Hotel Yilan': 'Yilan',
    'Lala Villa Kohlarn': 'Pattaya',
    'Lanna Hotel by Kasalong Resort and Spa Pattaya': 'Pattaya',
    'Lawinta Hotel Pattaya': 'Pattaya',
    'Le Bali Resort': 'Bali',
    'Le Chateau Lambousa Hotel': 'Chipre',
    'Le Meridien Goa': 'Goa',
    'Le Prive Resort': 'India',
    'Lemon Tree Hotel Anjuna Goa': 'Goa',
    "Let's Hyde Pattaya Resort & Villas": 'Pattaya',
    'Levana Pattaya Hotel': 'Pattaya',
    'Lewit Hotel Pattaya, a member of Radisson Individuals': 'Pattaya',
    'Lido Beach Hotel Pattaya': 'Pattaya',
    'Lill sparrow by The Verdant Escapes': 'Uttarakhand',
    'Little Mastiff Dharamshala Airport': 'Dharamshala',
    'Lords Inn Udaipur': 'Udaipur',
    'Lotusland Resort': 'Bali',
    'Lovina Beach Club & Resort': 'Bali',
    'Lovina Haven Boutique Resort': 'Bali',
    'Lovina Loca': 'Bali',
    'Lovina Oasis': 'Bali',
    'Lovinalife Room & Cafe': 'Bali',
    'M CASA HOTEL PATTAYA': 'Pattaya',
    'M Pattaya Hotel': 'Pattaya',
    'M Place Pattaya': 'Pattaya',
    'MClub Del Golfo': 'Mallorca Island',
    'MIDO HOTEL PATTAYA': 'Pattaya',
    'Maan Vilas By Stone Wood Udaipur': 'Udaipur',
    'Magnifico INN Pattaya': 'Pattaya',
    'Mahua Monks -Villa Resort Udaipur': 'Udaipur',
    'Mamori House at Koh Larn': 'Pattaya',
    'Mandarin Eastville, Pattaya': 'Pattaya',
    'Marble Garden View Pattaya': 'Pattaya',
    'March Hotel Pattaya': 'Pattaya',
    'Marina Jomtien Beach': 'Pattaya',
    'Marine Beach Hotel Pattaya': 'Pattaya',
    'Marine Plaza Hotel Pattaya': 'Pattaya',
    'Marine Yensabai Hotel Pattaya': 'Pattaya',
    'Massarossa Pool Villa Pattaya': 'Pattaya',
    'Matcha House Jomtien Pattaya': 'Pattaya',
    'Mazrika Sesoko': 'Okinawa',
    'Medalio Resort Udaipur Shobhagpura': 'Udaipur',
    'Meitetsu Toyota Hotel': 'Toyota',
    'Mementos By ITC Hotels Ekaaya Udaipur': 'Udaipur',
    'Mera Mare Pattaya': 'Pattaya',
    'Mercure Ambassador Seoul Hongdae': 'Seoul',
    'Mercure Ambassador Seoul Magok': 'Seoul',
    'Mercure Rayong Lomtalay Villas & Resort': 'Rayong',
    'Mgh 114 Hotel Krishna Udaipur': 'Udaipur',
    'Milan Yilan': 'Yilan',
    'Mild Life Hostel Udaipur': 'Udaipur',
    'Mimpi Nyata Villa & Dive Center': 'Bali',
    'Mind Tourist Hotel': 'Seoul',
    'Modessa Island': 'Mindoro',
    'Mondrian Seoul Itaewon': 'Seoul',
    'Moustache Bhimtal Luxuria, Nainital': 'Bhimtal',
    'Moustache Select Udaipur': 'Udaipur',
    'Moustache Udaipur Luxuria': 'Udaipur',
    'Moustache Udaipur Verandah': 'Udaipur',
    'Mu Jiao Xi Hotel': 'Yilan',
    'Munnar Jungle Camp': 'Munnar',
    'Mushroom House Kohlarn': 'Pattaya',
    'My Downtown - Prime A Premium Boutique Hotel Udaipur': 'Udaipur',
    'Mystical Valley View Resort and Spa, Udaipur': 'Udaipur',
    'Mytt Hotel Pattaya': 'Pattaya',
    'Mövenpick Siam Na Jomtien Pattaya': 'Pattaya',
    'NOA HOTEL Toyotaminami - Adults Only': 'Toyota',
    'NUB INN': 'Aswan',
    'Nalanta Pattaya Hotel': 'Pattaya',
    'Narayans Leela Inn By SGOH': 'India',
    'Navana Nature Escape': 'Darjeeling',
    'Neat House Hongdae': 'Seoul',
    'Neelesh Inn - Luxury Lake View Hotel With Swimming Pool On Bhimtal Lake': 'Bhimtal',
    'Nestonature Glamping Dharamshala': 'Dharamshala',
    'Netley Hall': 'Southampton',
    'Newel Psychiko': 'Athens',
    'Nglaras Resort Yogyakarta': 'Yogyakarta',
    'Nice Resort Pattaya': 'Pattaya',
    'Nightcap at Empire Hotel': 'Australia',
    'Nine Brick Hotel': 'Seoul',
    'Nine Rooms Trento': 'Trento',
    'Nine Star Hotel Sinchon': 'Seoul',
    'Nong Apartment Pattaya - Adults Only': 'Pattaya',
    'Norbu The Montanna, Dharamshala - IHCL SeleQtions': 'Dharamshala',
    'North Wing Canggu Resort': 'Bali',
    'NorthPoint Pattaya with Sea View': 'Pattaya',
    'Novotel Ambassador Seoul Yongsan - Seoul Dragon City': 'Seoul',
    'Novotel Lubumbashi': 'Lubumbashi',
    'Nubateera': 'Aswan',
    'Nukkad Guest House Near Lake Pichola': 'Udaipur',
    'O-Bay Design HotelPrachuap': 'Prachuap Khiri Khan',
    'OYO 10319 Hotel Pichola Haveli': 'Udaipur',
    'OYO 143 Dday Resotel Pattaya Hotel': 'Pattaya',
    'OYO 145 Pattaya Bed Boutique': 'Pattaya',
    'OYO 520 Pattaya Cantina': 'Pattaya',
    'OYO 698 Pattaya City': 'Pattaya',
    'OYO 75486 Anna Residence Jomtien': 'Pattaya',
    'OYO 830 Kohlarn Mountain': 'Pattaya',
    'OYO 917 PK Residence Pattaya': 'Pattaya',
    'OYO 93482 Penginapan Tenang Lovina': 'Bali',
    'OYO Life 91239 Kost Rosandy House Yogyakarta': 'Yogyakarta',
    'OZO North Pattaya': 'Pattaya',
    'Ocean Paradise Bali': 'Bali',
    'Old Faithful Inn - Inside the Park': 'Yellowstone',
    'Olympia Hotel at Capitol Lake': 'Olympia',
    'Omunity Bali': 'Bali',
    'One Patio Hotel Pattaya': 'Pattaya',
    'Onyado Nono Sendai Hot Spring': 'Sendai',
    'Ooedo Onsen Monogatari Premium Sendai Sakunami': 'Sendai',
    'Opal Motel': 'Australia',
    'Opal Private Nubian Hotel': 'Aswan',
    'Orange Inn Sendaihigashi': 'Sendai',
    'Orient Luxury Hotel-Jiao Xi': 'Yilan',
    'P-Park Hotel Pattaya': 'Pattaya',
    'PUERTO LACAR LODGE SMARG': 'San Martín de los Andes',
    'Paandora Grand Udaipur': 'Udaipur',
    'Padmasari Resort Hotel': 'Bali',
    'Palace Inn Toyota': 'Toyota',
    'Palm Beach Villas Bali': 'Bali',
    'Pandawa Village': 'Bali',
    'Pande Guest House Pemuteran': 'Bali',
    'Paradise Park Jomtien by PSR ASIA': 'Pattaya',
    'Parallel Hotel Udaipur, a member of Radisson Individuals': 'Udaipur',
    'Parinya Hill Homestay & Cafe Koh Larn': 'Pattaya',
    'Parion Hotel': 'Canakkale',
    'Parion House Hotel': 'Canakkale',
    'Park Avenue': 'Seoul',
    'Pattaya Bed Boutique Sha': 'Pattaya',
    'Pattaya Charm': 'Pattaya',
    'Pattaya Park Beach Resort': 'Pattaya',
    'Pattaya at Nine': 'Pattaya',
    'Pavilion Farmstay Udaipur': 'Udaipur',
    'Pax Gk Confier Dharamshala': 'Dharamshala',
    'Pax Grand Blue Udaipur': 'Udaipur',
    'Pax Rafahiya Haveli Udaipur': 'Udaipur',
    'Penthouse Pattaya': 'Pattaya',
    'Petercat Hotel Sinchon (Hongdae)': 'Seoul',
    'Phan Loft Koh Larn': 'Pattaya',
    'Phoenix Unmatched Comfort - Hotel Near Fateh Sagar Lake Udaipur': 'Udaipur',
    'Phu View Talay Resort': 'Pattaya',
    'Pichcha Kohlarn': 'Pattaya',
    'Pichola Lake Retreat': 'Udaipur',
    'Pichola Vilas': 'Udaipur',
    'Plataran Menjangan Resort and Spa': 'Bali',
    'Pleasant View Resort': 'India',
    'Poinciana Resort Bali': 'Bali',
    'Polo Villa 1 by Avantstay Features Expansive Pool, Spa & Outdoor Firepit 260-322 5 Bedrooms': 'Coachella Valley',
    'Polo Villa 10 by Avantstay Backyard Oasis w/ Putting Green 260320 6 Bedrooms': 'Coachella Valley',
    'Polo Villa 11 by Avantstay Bright Interior w/ Outdoor Bocce Ball, Pool & Spa 260330 5 Bedrooms': 'Coachella Valley',
    "Polo Villa 2 by Avantstay Entertainer's Backyard w/ Pickleball Court, Pool & Spa 260314 6 Bedrooms": 'Coachella Valley',
    'Polo Villa 3 by Avantstay Backyard Retreat w/ Pool, Spa & Firepit 260328 6 Bedrooms': 'Coachella Valley',
    'Polo Villa 5 by Avantstay Outdoor Bocce Ball, Ping Pong Table, Pool & Spa 260332 6 Bedrooms': 'Coachella Valley',
    "Polo Villa 7 by Avantstay Features Entertainer's Backyard + Game Room 260316 5 Bedrooms": 'Coachella Valley',
    'Polo Villa 9 by Avantstay Backyard w/ Putting Green, Pool & Spa 5 BDR 260312': 'Coachella Valley',
    'Prachuap Beach Hotel': 'Prachuap Khiri Khan',
    'Prachuap Grand Hotel': 'Prachuap Khiri Khan',
    'Prachuap Saam Ao Hotel': 'Prachuap Khiri Khan',
    'Premier Inn Abergavenny': 'Gales',
    'Premier Inn Monmouth': 'Gales',
    'Premier Inn Oswestry': 'Gales',
    'Pride Hotel Udaipur': 'Udaipur',
    'Prima House Pattaya': 'Pattaya',
    'ProfilHotels Halmstad Plaza': 'Halmstad',
    'Puri Bali Lovina': 'Bali',
    'Puri Lovina': 'Bali',
    'Puri Mangga Sea View Resort & Spa': 'Bali',
    'RAC Margaret River Nature Park': 'Margaret River',
    'RQ North Pattaya By Collection O': 'Pattaya',
    'Raaya Resort Udaipur': 'Udaipur',
    'Radisson Blu Resort Dharamshala': 'Dharamshala',
    'Radisson Udaipur': 'Udaipur',
    'Raffles Udaipur': 'Udaipur',
    'Rajdarshan - A Lake View Hotel in Udaipur': 'Udaipur',
    'Ramada Encore by Wyndham Gimpo Han River Hotel': 'Seoul',
    'Ramada Seoul Sindorim Hotel': 'Seoul',
    'Ramada Suites by Wyndham Solo': 'Solo',
    'Ramada by Wyndham Goa Arpora': 'Goa',
    'Ramada by Wyndham La Verkin Zion National Park': 'Zion',
    'Ramada by Wyndham Yogyakarta': 'Yogyakarta',
    'Ramee Royal Resort & Spa Udaipur': 'Udaipur',
    'Ramee Wolkenburg Resort and Spa Munnar': 'Munnar',
    'Rang Noknoy Resort at Koh Larn': 'Pattaya',
    'Rawla Udaipur': 'Udaipur',
    'Red Roof Inn Dillon, SC': 'Red Roof Inn Dillon',
    'RedDoorz Syariah near Jogja City Mall 2': 'Yogyakarta',
    'RedDoorz near UMY Yogyakarta': 'Yogyakarta',
    'Regenta Central Mewargarh Udaipur': 'Udaipur',
    'Regenta Central Udaipur': 'Udaipur',
    'Regina Resort El sokhna': 'Ain Sokhna',
    'Residence Inn by Marriott San Jose North/Silicon Valley': 'San Jose - Silicon Valley',
    'Resort Style Tuscan Living with Spa Pool & Firepit': 'Coachella Valley',
    'Resorts By The Baagh Bhimtal': 'Bhimtal',
    'Retreat Resort Pattaya': 'Pattaya',
    'Richmond Hotel Premier Sendai Ekimae': 'Sendai',
    'Richmond Hotel Sendai': 'Sendai',
    'Rifugio Viote': 'Trento',
    'Rimtalay Resort Koh Larn': 'Pattaya',
    'Rising Sun Motor Inn and Cabins - Inside the Park': 'Glacier National Park',
    'RnB Shivani Udaipur': 'Udaipur',
    'Room Kohlarn Resort': 'Pattaya',
    'Rosefinch Sarovar Portico Bhimtal': 'Bhimtal',
    'Rosewood Retreat Bhimtal': 'Bhimtal',
    'Rouista Tzoumerka Resort': 'Grecia',
    'Royal Cliff Beach Terrace Hotel Pattaya': 'Pattaya',
    'Royal Palace Hotel Pattaya': 'Pattaya',
    'Royal Prince Resort Pattaya': 'Pattaya',
    'Royal Rafahiya - A Rooftop Lake View Hotel Near Lake Pichola': 'Udaipur',
    'Royal Square Hotel Seoul': 'Seoul',
    'Royal Star Suites Pattaya': 'Pattaya',
    'Ruenthip Residence Pattaya': 'Pattaya',
    'Rumah Gajah by Kubukubali': 'Bali',
    'Rumput Resort & Resto': 'Bali',
    'S Lodge Pattaya (formally known as Sabai Lodge)': 'Pattaya',
    'SPOT ON 92068 Pudja Kesuma Homestay Syariah Yogyakarta': 'Yogyakarta',
    'SPOT ON 93592 Pondok Backpackers Ardafa JogjaNearBlue Lagoon Jogja': 'Yogyakarta',
    'SRINN Hotel Pattaya Klang': 'Pattaya',
    'SUPER HOTEL Premier Sendai Kokubuncho Natural Hot Spring': 'Sendai',
    'SUPER HOTEL Sendai station east Natural Hot Spring': 'Sendai',
    'Sagar Villa Udaipur': 'Udaipur',
    'Sailor Hotel Pattaya': 'Pattaya',
    'Samsara Hotel Pattaya': 'Pattaya',
    'Sanco Inn Toyota': 'Toyota',
    'Sarasiruham Resort - Private Pool Villa in Udaipur': 'Udaipur',
    'Sasando Residence Kupang': 'Kupang',
    'Satoria Hotel Yogyakarta': 'Yogyakarta',
    'Sayaji Resort and Spa Udaipur': 'Udaipur',
    'Scenic, Munnar - IHCL SeleQtions': 'Munnar',
    'Schlosshotel Marienbad': 'Marienbad',
    'Sea Crest By Jomtien': 'Pattaya',
    'Sea Inn Pattaya': 'Pattaya',
    'Sea Me Spring Tree Hotel - Adults only': 'Pattaya',
    'Sealey Resort Koh Larn': 'Pattaya',
    'Seasons Boutique Hotel near Sajjangarh Biological Park, Udaipur': 'Udaipur',
    'Seehotel am Tankumsee': 'Wolfsburg',
    'Selina Place Pattaya': 'Pattaya',
    'Sendai Kokusai Hotel': 'Sendai',
    'Serenity Hill Resort Near - 2Km Fateh Sagar Lake Udaipur': 'Udaipur',
    'Shagwell Mansions Pattaya': 'Pattaya',
    'Shambhala Hotel Pattaya': 'Pattaya',
    'Shamrock Hotel Pattaya': 'Pattaya',
    'Shankara Munduk Bali': 'Bali',
    'Sherwood View Accommodation': 'Australia',
    'Shilla Stay Guro': 'Seoul',
    'Shilla Stay Mapo': 'Seoul',
    'Shilla Stay Seocho Gangnam Station': 'Seoul',
    'Silks Place Yilan': 'Yilan',
    'Silver Oasis Maldives': 'Maldivas',
    'Sinclairs Palace Retreat Udaipur': 'Udaipur',
    'Sinclairs Udaipur': 'Udaipur',
    'Six Senses Shaharut': 'Israel',
    'Sky hip resort jomtean pattaya': 'Pattaya',
    'Sleep With Me Pattaya': 'Pattaya',
    'Smart Place Pattaya': 'Pattaya',
    'Smile Hotel Otsu Seta': 'Otsu',
    'Smile Hotel Sendai Kokubuncho': 'Sendai',
    'Sofitel Inle Lake Myat Min Hotel': 'Inle Lake',
    'Soham Haveli Udaipur': 'Udaipur',
    'Soi 2 inn Pattaya': 'Pattaya',
    'Solares Cumbrecita': 'Cumbrecita',
    'Sotetsu Fresa Inn Sendai': 'Sendai',
    'Sotis Hotel Kupang': 'Kupang',
    'Spacious 2 BR at Water Side El Gouna': 'El Gouna',
    'Spectrum Resort & Spa, Udaipur': 'Udaipur',
    'Sporthotel Malchow': 'Mecklenburg',
    'Spring Sky Udaipur by ShriGo Hotels': 'Udaipur',
    'Star Hotel Pattaya': 'Pattaya',
    'Stay Hotel Gangnam': 'Seoul',
    'Stay Inn Hotel - Ain Sokhna': 'Ain Sokhna',
    'Stay Resort Pattaya': 'Pattaya',
    'Staybridge Suites Eastvale Norco by IHG': 'Los Angeles (and vicinity), CA, US',
    'Sterling Aravalli Udaipur': 'Udaipur',
    'Sterling Balicha Udaipur': 'Udaipur',
    'Sterling Jaisinghgarh Udaipur': 'Udaipur',
    'Stone Wood Beach Resort': 'Goa',
    'Storica Stays Panorama Haveli Udaipur': 'Udaipur',
    'Storii By ITC Hotels Amoha Retreat, Dharamshala': 'Dharamshala',
    'Sukkeebeach Kohlarn Resort': 'Pattaya',
    'Sun and Sea Kohlarn': 'Pattaya',
    'Suncity Hotel Pattaya': 'Pattaya',
    'Sunday Chateau En Ville Pattaya': 'Pattaya',
    'Sunday Grand Jomtien Pattaya': 'Pattaya',
    'SureStay Plus by Best Western T Pattaya': 'Pattaya',
    'Swantown Inn': 'Olympia',
    'Swiftcurrent Motor Inn and Cabins - Inside the Park': 'Glacier National Park',
    'Swiss-Belcourt Kupang': 'Kupang',
    'T2 Jomtien Pattaya': 'Pattaya',
    'THE JJ CORBETT BLISS': 'Jim Corbett',
    'TOLIP Resort El Galala Majestic': 'Ain Sokhna',
    'Teluk Karang Dive and Spa Resort Bali': 'Bali',
    'The  Seathru  Kohlarn': 'Pattaya',
    'The AGATE Pattaya Boutique Resort': 'Pattaya',
    'The Atrium Hotel and Resort Yogyakarta': 'Yogyakarta',
    'The Beach Front Resort Pattaya  - SHA Plus': 'Pattaya',
    'The Cabin Hotel Lovina Bali': 'Bali',
    'The Cangkringan Jogja Villas & Spa': 'Yogyakarta',
    'The Castle Villa Udaipur': 'Udaipur',
    'The ChanThong Hotel Pattaya': 'Pattaya',
    'The Chronicles by WSI - Near the Lake Pichola Udaipur': 'Udaipur',
    'The Classic Crown Udaipur - A Luxury Hotel by Lake Pichola': 'Udaipur',
    'The Crescent Udaipur | Boutique Hotel Near Lake Pichola': 'Udaipur',
    'The Designers LYJ Gangnam Premier': 'Seoul',
    'The Divine Hills Resort Udaipur': 'Udaipur',
    'The ESSE Hotel Pattaya': 'Pattaya',
    'The Elysium Pratumnak Pattaya - By SHG': 'Pattaya',
    'The Fern Bambora Fort Udaipur, Bambora, Series by Marriott': 'Udaipur',
    'The Fern Hillside Resort Bhimtal': 'Bhimtal',
    'The Fern Residency Bhuj': 'Bhuj',
    'The Fern Residency Udaipur, Series by Marriott': 'Udaipur',
    'The Gems Mining Pool Villas Pattaya': 'Pattaya',
    'The Grand Lodge Pattaya': 'Pattaya',
    'The Heritage Pattaya Beachfront Resort': 'Pattaya',
    'The Heron House': 'Maine',
    'The Hideaway Resort Pattaya Chonburi': 'Pattaya',
    'The Hotel Route-Inn Sendai Higashi': 'Sendai',
    'The Jagat Hotel and Spa Udaipur': 'Udaipur',
    'The KN Kohlarn': 'Pattaya',
    'The LD Pattaya': 'Pattaya',
    'The Lake Heritage @Bhimtal Lake': 'Bhimtal',
    'The Lake View Hotel – On Lake Pichola': 'Udaipur',
    'The Leela Palace Udaipur': 'Udaipur',
    'The Light House Resort - Kohlarn': 'Pattaya',
    'The Local Menjangan': 'Bali',
    'The Lodge Jomtien 7': 'Pattaya',
    'The Lodge Jomtien 9': 'Pattaya',
    'The Lodge Pattaya': 'Pattaya',
    'The Manja Retreat Lovina Bali': 'Bali',
    'The Moment Hotel Yilan by Lakeshore': 'Yilan',
    'The Montail Udaipur': 'Udaipur',
    'The Monttra Pattaya': 'Pattaya',
    "The Nature's Green Resort -Bhimtal": 'Bhimtal',
    'The O Villa Jiaoxi': 'Yilan',
    'The OneFive Sendai': 'Sendai',
    'The Paradise Bliss - A Luxury Hotel & Spa in Udaipur': 'Udaipur',
    'The Park Classic Udaipur': 'Udaipur',
    'The Park Pattaya': 'Pattaya',
    'The Proud Hotel Pattaya': 'Pattaya',
    'The Quba Boutique Hotel Pattaya': 'Pattaya',
    'The Ramvilas - A Rooftop Lake View Hotel in Udaipur': 'Udaipur',
    'The Rangers reserve Jim Corbett': 'Jim Corbett',
    'The Riviera Wongamat by Pattaya Holiday': 'Pattaya',
    'The Royal Adobe Pattaya': 'Pattaya',
    'The Sala Pattaya': 'Pattaya',
    'The Sanctuary Resort Pattaya, BW Signature Collection': 'Pattaya',
    'The Sky Imperial Udaipur': 'Udaipur',
    'The Sloop Inn': 'Cornwall',
    'The Tamnan Pattaya Hotel & Resort': 'Pattaya',
    'The Udaipur Luxurious Villa Udaipur': 'Udaipur',
    'The Vaag Udaipur A Luxury Pool Villa in Udaipur': 'Udaipur',
    'The Westin Yilan Resort': 'Yilan',
    'The Westlake Hotel & Resort Yogyakarta': 'Yogyakarta',
    'The Windy Mist Resort Munnar': 'Munnar',
    'The Zen Hotel Pattaya': 'Pattaya',
    'The Zign Hotel': 'Pattaya',
    'The central lovina hotel & restaurant': 'Bali',
    'Thorn Hill Vineyard Villas': 'Temecula',
    'Ti amo Kohlarn': 'Pattaya',
    'Tiny Home Resorts': 'USA',
    'Tiny Home Vacations Resort': 'USA',
    'Tirta Sari Bungalows & Spa': 'Bali',
    'Tolip Resort Elgalala Hills': 'Ain Sokhna',
    'Toonja kohlarn': 'Pattaya',
    'Tourist Settlement Brzet': 'Croacia',
    'Towneplace Suites By Marriott Toledo Perrysburg': 'Toledo',
    'Toyoko Inn Kyoto Biwako Otsu': 'Kyoto',
    'Toyoko Inn Sendai Higashi 2': 'Sendai',
    'Toyoko Inn Sendai Higashi-guchi No.1': 'Sendai',
    'Toyoko Inn Sendai Nishi Hirose Dori': 'Sendai',
    'Toyoko Inn Seoul Gangnam': 'Seoul',
    'Toyoko Inn Toyota-shi Ekimae': 'Toyota',
    'Toyota Prestige Hotel': 'Toyota',
    'Trang blue hotel': 'Trang',
    'Tree of Life Amara Resorts & Spa Udaipur': 'Udaipur',
    'Treebo The Fresco Lake Pichola': 'Udaipur',
    'Tribe Pattaya': 'Pattaya',
    'Trijaya Guest House': 'Bali',
    'Tsix5 Phenomenal Hotel Pattaya': 'Pattaya',
    'Turban Roopgarh Resort and Spa, Udaipur': 'Udaipur',
    'Tycoon Suite Pattaya': 'Pattaya',
    'Udai Nature Valley Resort Udaipur': 'Udaipur',
    'Uddhav Vilas': 'Varanasi',
    'Unique Regency Pattaya': 'Pattaya',
    'V Style Pattaya North Beach': 'Pattaya',
    'VR-Ain Sokhna Chalet': 'Ain Sokhna',
    'VR-Alhayat Ain El Sokhna': 'Ain Sokhna',
    'VR-Apartment Overlooking Pool & Lagoon': 'El Gouna',
    'VR-Blue Bay Asia Resort El Sokhna': 'Ain Sokhna',
    'VR-Buena Vista by Avantstay Massive Outdoor Oasis w/ Pool, Spa & Firepit!': 'Coachella Valley',
    'VR-Casa Serenity Luxury Living w/ Pool & Jacuzzi': 'Coachella Valley',
    'VR-Casa del Arbol by Avantstay Stunning California Estate With Incredible Views': 'Temecula',
    'VR-Chalet In Belagio Ain Sokhna': 'Ain Sokhna',
    'VR-Charming Villa in El Gouna with Pool': 'El Gouna',
    'VR-Chestnuthill Countryside Manor': 'Pocono Mountains',
    'VR-Cloud9 Coachella': 'Coachella Valley',
    'VR-Colina by Avantstay Secluded Mountain Top Oasis w/ Pool, Hot Tub & Putting Green!': 'Coachella Valley',
    'VR-Costa Bella Condominiun Resort': 'Philippines',
    'VR-De Luz by Avantstay 5 Acre Estate w/ Lake, Pool & Hot Tub': 'Temecula',
    'VR-Eagle River Vacation Home': 'Eagle River',
    'VR-El Gouna Rental Smokery Beach Apartment': 'El Gouna',
    'VR-El Reino by Avantstay Spectacular Estate w/ Pool & Tennis Court!': 'Temecula',
    'VR-Extremely Private Villa With Optional Pool Heating': 'El Gouna',
    'VR-Fadlos Anay Nubian Guesthouse': 'Aswan',
    'VR-Feel Above it All in Utah!': 'Zion',
    'VR-Global Luxury Suites Sunnyvale North': 'San Jose - Silicon Valley',
    'VR-Indian Palms Oasis - Just a Walk to Festivals!': 'Coachella Valley',
    'VR-Ken Ken Villa Yuumodoro': 'Okinawa',
    'VR-Kite & Beach Apartment in Mangroovy': 'El Gouna',
    'VR-La Barrique by Avantstay Secluded 14 Acre Estate w/ Vball & Pool': 'Coachella Valley',
    'VR-Lagoon Villa in El Gouna': 'El Gouna',
    'VR-Lakeside in the Desert': 'Coachella Valley',
    'VR-Luxurious Villa Living in Indio w/ Pool/Spa': 'Coachella Valley',
    'VR-Marilyn by Avantstay Mins to Old Town La Qunita!': 'Coachella Valley',
    'VR-Merlot by Avantstay Exquisite Home w/ Pool and Stunning Patio': 'Coachella Valley',
    'VR-Paraiso de Motobu': 'Okinawa',
    'VR-Saltwater Suites': 'Maine',
    'VR-Stunning Golf Villa in El Gouna': 'El Gouna',
    'VR-Sunset Hideaway Near National Parks & Hike/bike': 'Zion',
    'VR-Sweet Retreat Rest & Relax Near National Parks': 'Zion',
    'VR-The Berri Bubble Lodge': 'Australia',
    'VR-The Pool & Sauna Villa MOTOBU': 'Okinawa',
    'VR-The Riesling Retreat by Avantstay Estate w/ Pool, Hottub, Putting Green & Pickle Ball Court!': 'Coachella Valley',
    'VR-VESTA - El Gouna Residence': 'El Gouna',
    'VR-Warhol by Avantstay Expansive Estate Stunning Wine Cty Views': 'Coachella Valley',
    'VR-Whitefish Stage Hideaway': 'Whitefish',
    'VS Beach Front Pattaya': 'Pattaya',
    'Vaibhavya Hotel and Restaurant-Udaipur': 'Udaipur',
    'Valhalla Pattaya Hotel': 'Pattaya',
    'Vanko International Hotel Pattaya': 'Pattaya',
    'Veranda Resort Pattaya - MGallery Collection': 'Pattaya',
    'Veronica Resort , BY THE  BEACH': 'Goa',
    'Vesta - Luxury Villa - 4 BR - Nubia': 'Aswan',
    'Vesta Grand Central Udaipur': 'Udaipur',
    'Vibe Munnar Resort & Spa': 'Munnar',
    'Vijaygarh Resort & Cottages with Private Pool': 'India',
    'Villa Inn Udaipur by Yansh Group': 'Udaipur',
    'Villa Inn-Adult Only- Temecula Wine Country': 'Temecula',
    'Villa Lamai - Wong Amat House Pattaya': 'Pattaya',
    'Villa Le Palm - Luxury Resort Near Fateh Sagar Lake (3 KM) Udaipur': 'Udaipur',
    'Villa Misk': 'Arabia Saudita',
    'Villa Oranje Pattaya': 'Pattaya',
    'Villas del Malbec Lodge': 'Mendoza',
    'Virawan pool resort kohlarn': 'Pattaya',
    'Vista Valley Stay - Dharamshala': 'Dharamshala',
    'Vivir Jiaoxi Hotel': 'Yilan',
    'Voco Seoul Gangnam': 'Seoul',
    'W14 Pattaya': 'Pattaya',
    'W1A Jomtien': 'Pattaya',
    'Wan DD Resort Kohlarn': 'Pattaya',
    'Wapnö Gårdshotell': 'Halmstad',
    'Washington R&B Hotel Sendai Higashiguchi': 'Sendai',
    'Welcome Jomtien Beach Hotel': 'Pattaya',
    'Wellspring by Silks Jiao Xi': 'Yilan',
    'Welnez World Residence Pattaya': 'Pattaya',
    'Whitehouse Condotel': 'Pattaya',
    'Windale Resorts Munnar': 'Munnar',
    'Woodspring Suites Corona': 'Los Angeles (and vicinity), CA, US',
    'Wyatt Hotel Jomtien Beach': 'Pattaya',
    'Wyndham Garden Yogyakarta': 'Yogyakarta',
    'Wyndham Grand Nai Harn Beach Phuket': 'Phuket',
    'Wyndham Jomtien Pattaya': 'Pattaya',
    'X Hotel Pattaya': 'Pattaya',
    'XQ Pattaya Hotel': 'Pattaya',
    'Xenious Micro Villas Goa': 'Goa',
    "Y's house in Hongdae": 'Seoul',
    'YAAN Udaipur': 'Udaipur',
    'Yeouido Park Centre, Marriott Executive Apartments': 'Seoul',
    'Yilan Feeling Homestay B&B': 'Yilan',
    'Yilan Greenbird of Happiness B&B': 'Yilan',
    'Yilan Jimmy Villa': 'Yilan',
    'Yilan Siao Jhu': 'Yilan',
    'Yilan Xiang Feng Homestay': 'Yilan',
    'Yogyakarta Marriott Hotel': 'Yogyakarta',
    'Yumoto Hotel Achikawa': 'Tokyo',
    'ZIP Hotel': 'Seoul',
    'Zana Lake Resort Udaipur': 'Udaipur',
    'Zion White Bison': 'Zion',
    'Zubani hotel and suites': 'Enugu',
    'blackwoods Hotel Pattaya': 'Pattaya',
    'bloomrooms @ Calangute': 'Goa',
    'ibis Styles Athens Routes': 'Athens',
    'juSTa Luxe Sajjangarh Resort & Spa, Udaipur': 'Udaipur',
    'lebua Udaipur Daulatgarh': 'Udaipur',
    'samastiti lovina': 'Bali',
    'steinhorst hotel': 'Wolfsburg',
}
