# dest_mapping.py — auto-mapper + revisión manual Fede
# 1461 hoteles mapeados

DEST_MAPPING = {
    '12HEH Pattaya': 'Pattaya',
    '19 Belo Cabana': 'Goa',
    '22°C Cold Spring Hotel': 'Yilan',
    '58mutian B&B': 'Yilan',
    '7 Days Premium Hotel Pattaya': 'Pattaya',
    '7 Rays Hotel': 'Udaipur',
    '89 HAPPY BNB': 'Yilan',
    '8fold-Pinecrest By LaRiSa, Bhimtal': 'Bhimtal',
    '9 Karat Condo by PSR': 'Pattaya',
    '9 Tan Yuan Homestay': 'Yilan',
    '99 Guest House': 'Phuket',
    '9h nine hours Sendai': 'Sendai',
    '@HOME by Best Western St. George': 'St. George',
    '@T Boutique Hotel': 'Prachuap Khiri Khan',
    'A-SAN Hot Spring Hotel': 'Yilan',
    'A.A. Pattaya Golden Beach Hotel': 'Pattaya',
    'A2Sea Hotel': 'Pattaya',
    'AOIKE Hot Spring Hotel': 'Yilan',
    'APA Hotel TKP Sendai-Ekikita': 'Sendai',
    'ASPEN HOTEL ÇANAKKALE': 'Canakkale',
    'Aaj Haveli - A Luxury Boutique Hotel': 'Udaipur',
    'Aamod Feather Touch': 'Nainital',
    'Aangan Palace': 'Udaipur',
    'Aangan Royal Stay - Your Mountain Home in Dharamshala': 'Dharamshala',
    'Aaroham By Aamod Dharamshala': 'Dharamshala',
    'Aaroham The Watergate Hotel': 'Bhimtal',
    'Abani Jomtien Inn': 'Pattaya',
    'AbhiRaj Villa': 'Udaipur',
    'Acanti Dharamshala': 'Dharamshala',
    'Achawalai By PP': 'Pattaya',
    'Adiwana Dara Ayu': 'Bali',
    'Adriatic Palace Hotel Pattaya': 'Pattaya',
    'Adrushya Estate Luxury Suites Mukteshwar': 'Mukteshwar',
    'Agariya Haveli Hotel And Restaurant': 'Udaipur',
    'Aires Serranos - Suites': 'Córdoba',
    'Aitken Hill': 'Melbourne',
    'Akara Hotel Pattaya': 'Pattaya',
    'Akira Pattaya': 'Pattaya',
    'Akiu Onsen Hotel Hananoyu': 'Japan',
    'Akiu Resort Hotel Crescent': 'Japan',
    'Alam Jogja Resort': 'Yogyakarta',
    'Alamanda Lovina Resort': 'Bali',
    'Alassari Plantation': 'Bali',
    'Alcove Resort': 'Yilan',
    'Alivaa Hotel, McLeodganj With Best Dhauladhar View & Infinity Pool Sky Garden': 'Dharamshala',
    'All-Ur Boutique Motel - Hua-Lian Branch': 'Hualien',
    'All-Ur Boutique Motel - Yi-Lan Branch': 'Yilan',
    'Almont Hotel Sendai': 'Sendai',
    'Alta Gracia Parque Hotel': 'Alta Gracia',
    'Amanti Hotel Seoul': 'Seoul',
    'Amantra Shilpi Resort & Spa': 'Udaipur',
    'Amaranta Prambanan Yogyakarta': 'Yogyakarta',
    'Amaya Suites': 'India',
    'Amethyst Hotel Pattaya': 'Pattaya',
    'Amiigo Kohlarn': 'Pattaya',
    'An Lam Retreats Ninh Van Bay': 'Nha Trang',
    'Anakato': 'Aswan',
    'Anandam - A Luxury resort in Udaipur': 'Udaipur',
    'Anant Vilas Resort': 'Udaipur',
    'Anantra Resort Pattaya': 'Pattaya',
    'Andeluna Winery Lodge': 'Mendoza',
    'Andores Resort And Spa': 'Goa',
    'Angels Inn Jiaoxi Hotspring': 'Yilan',
    'Anook Hotel Suwon Ingye': 'Suwon',
    'Anook Ryokan and Anook Air Cheongju': 'Cheongju',
    'Ansan Hotel 727': 'Ansan',
    'Ansan Hotel Wol': 'Ansan',
    'Ansan Queens Hotel': 'Ansan',
    'Ansan Rosa Bell Hotel': 'Ansan',
    'Ansan Seowon Hotel': 'Ansan',
    'Anshan Hotel BIZ': 'Ansan',
    'Anshan Hotel Sense': 'Ansan',
    'Anvaya Udaipur - Steps from Lake Pichola, Old City': 'Udaipur',
    'Aotel Pangot (Formerly Royal Cliff)': 'Pattaya',
    'Apart Hotel La Bora': 'Argentina',
    'Arainn Bed And Breakfast Tretes Prigen by ecommerceloka': 'Surabaya',
    'Aranya Vilas': 'Udaipur',
    'Aravali Marriott Resort & Spa, Delhi NCR': 'Nueva Delhi',
    'Arawana Express North Pattaya': 'Pattaya',
    'Arawana Regency North Pattaya': 'Pattaya',
    'Arawana Regency South Pattaya': 'Pattaya',
    'Arbour Hotel And Residence Pattaya': 'Pattaya',
    'Arcadia Mansion': 'Pattaya',
    'Archontiko Galliaki in Crete': 'Creta',
    'Arden Hotel and Residence': 'Pattaya',
    'Ardency Inn by Park Tree Udaipur': 'Udaipur',
    'Argo Pattaya Resort and Villas': 'Pattaya',
    'Armida City Hotel': 'Canakkale',
    'Artyzen Habitat Chongqing': 'Chongqing',
    'Aruvi Resort Munnar': 'Munnar',
    'Aryston Hotel Udaipur': 'Udaipur',
    'Asana Hotel & Residence': 'Pattaya',
    'Ascent Premiere Pasuruan': 'Surabaya',
    'Ascott Raffles City Chongqing': 'Chongqing',
    'Aster Hotel and Residence': 'Pattaya',
    'Aswan Cozy Apartment.': 'Aswan',
    'At Inn Hotel Toyotashi station': 'Toyota',
    'At Sea Hotel Pattaya': 'Pattaya',
    'Atlantis Condo and Water Park Pattaya by the Sea': 'Pattaya',
    'Atlantis by PSR': 'Pattaya',
    'Atman Resort Dharamshala By Leisure Hotels': 'Dharamshala',
    'Atthebeach Kohlarn': 'Pattaya',
    'Atulya Niwas, Udaipur': 'Udaipur',
    'Auberge Homachi Mikuniminato': 'Mikuni',
    'Aurika, Udaipur - Luxury by Lemon Tree Hotels': 'Udaipur',
    'AutoCamp Zion': 'Zion',
    'Avadale Munnar - Stag Groups Not Allowed': 'Munnar',
    'Avana Hotel Pemuteran': 'Bali',
    'Avexia Elite Resort & Spa Udaipur': 'Udaipur',
    'Azzure By Spree Goa': 'Goa',
    'B&B Hotel Wolfsburg-Weyhausen': 'Wolfsburg',
    'B&B PIEDICASTELLO': 'Trento',
    'B2 Hotel South Pattaya Premier Hotel': 'Pattaya',
    'BIG4 Frankston Holiday Park': 'Melbourne',
    'BON Hotel Rustenburg': 'Rustenburg',
    'Baan Coconut At Koh Larn': 'Pattaya',
    'Baan I Taley On Sea': 'Pattaya',
    'Baan Pattaya by Sabai': 'Pattaya',
    'Baan Talay': 'Pattaya',
    'Babylon Residence Inn pattaya': 'Pattaya',
    'Badi Garh Resort': 'Udaipur',
    'Bagus Homestay Pemuteran': 'Bali',
    'Bakubung Villas': 'Sudáfrica',
    'Bali Menjangan Boutique Villas': 'Bali',
    'Bali au Naturel - Adults Only': 'Bali',
    'BaliTrekk Boutique Hotel': 'Bali',
    'Bamboo Saa Resort & Spa - Udaipur': 'Udaipur',
    'Banana Guesthouse South Pattaya': 'Pattaya',
    'Beachwalk Jomtien': 'Pattaya',
    'Bear Creek Guest Ranch': 'Montana',
    'Beargrass Lodging and RV Resort': 'Montana',
    'Bears Den Pattaya': 'Pattaya',
    'Beauty Garden Hotel Jiaoxi': 'Yilan',
    'Belvilla Ananda Resort Lovina BeachNearPantai Lovina': 'Bali',
    'Belvilla Calm Haven Amabela Garden Lovina BeachNearLovina Beach': 'Bali',
    'Benada Piyungan Yogyakarta by ABM': 'Yogyakarta',
    'Benben By Dhara Hotels': 'Aswan',
    'Bensri Residence Pattaya': 'Pattaya',
    'Best Western Ebbw Vale': 'Gales',
    'Best Western Plus Coachella Valley Inn & Suites': 'Coachella Valley',
    'Beston Pattaya': 'Pattaya',
    'Beverly Mountain Bay, Trademark Collection By Wyndham': 'Pattaya',
    'Bhanwar Singh Palace Pattaya': 'Pattaya',
    'Bhraj Inn Hotel Udaipur': 'Udaipur',
    'Biorock Homestay': 'Bali',
    'Birds and Bees Resort': 'Pattaya',
    'Biwako Grand Hotel': 'Japan',
    'Biwako Mastunoura Bettei': 'Japan',
    'Bkl Pool Villa Pattaya': 'Pattaya',
    'Blanc Hotel Cheongju': 'Cheongju',
    'Bliss Mansion': 'Pattaya',
    'Bloom Boutique | Lake Pichola': 'Udaipur',
    'BloomSuites Calangute': 'Goa',
    'BluSalzz Collection Suvaasa - Ramgarh': 'Uttarakhand',
    'Blue Bed Pattaya SHA by Zuzu': 'Pattaya',
    'Blue Garden Resort Pattaya': 'Pattaya',
    'Bo Jue Farm Stay': 'Yilan',
    'Bondalem Beach Club': 'Bali',
    'Boulders Safari Lodge': 'Kruger',
    'Boulevard Munnar': 'Munnar',
    'Boutique City And Bravo Hotel Pattaya': 'Pattaya',
    'Brahma Niwas - Best Lake View Hotel in Udaipur': 'Udaipur',
    'Breezy Pattaya': 'Pattaya',
    'Brighthouse': 'Yilan',
    'Brighton Grand Hotel Pattaya': 'Pattaya',
    'Brij Atmanya, Bhowali | A Luxury Mountain Escape': 'Nainital',
    'British Hotel Girne': 'Chipre',
    'Bua Tara Resort': 'Pattaya',
    'Bucheon A Hotel': 'Bucheon',
    'Bucheon Hotel Ben': 'Bucheon',
    'Budget Motel Granite City/St Louis Area': 'St. Louis',
    'Bujera Fort': 'Udaipur',
    'Burans Kot Heritage Home - Ramgarh': 'Uttarakhand',
    'Business Hotel Kosanagi': 'Toyota',
    'Buubble Hotel - Hrosshagi': 'Islandia',
    'By Dee @Jomtien': 'Pattaya',
    'CASA DUMAI OceanVilla NAKIJIN': 'Japan',
    'CHONGQING MANQUE MANSION': 'Chongqing',
    'CK Resort Pattaya': 'Pattaya',
    'CNHOL Hotel - Chongqing Huanancheng': 'Chongqing',
    'COSI Pattaya Wong Amat Beach': 'Pattaya',
    'CU at Jomtien': 'Pattaya',
    'Cabinas Arenal Home': 'Arenal',
    'Cai Yeye B&B': 'Yilan',
    'Campestral Garden B&B': 'Yilan',
    'Cancun Sokhna Resort & Villas': 'Ain Sokhna',
    'Cape Montenegro Villas': 'Montenegro',
    'Capital O 94018 Joglo Eyang Niek Turi Syariah': 'Yogyakarta',
    "Casa Palmera by Avantstay Entertainer's Oasis w/ Guesthouse": 'Coachella Valley',
    'Castle Oodeypore A Boutique Stay Udaipur': 'Udaipur',
    'Caviar Kohlarn': 'Pattaya',
    'Center Hotel Toyota': 'Toyota',
    'Centre Point Prime Hotel Pattaya': 'Pattaya',
    'Chandra Vilas Heritage stay': 'Udaipur',
    'Chandralok - A Boutique Hotel in Udaipur Near Fateh Sagar Lake': 'Udaipur',
    'Charinn Kohlarn': 'Pattaya',
    'Charm Hostel at Jomtien': 'Pattaya',
    'Charm Hostel at Pratumnak': 'Pattaya',
    'Check-in Resort Koh Larn': 'Pattaya',
    'Cheongju Hotel Dictionary': 'Cheongju',
    'Cheongju Maryjane Hotel': 'Cheongju',
    'Cherry Valley Manor Luxury Bed and Breakfast': 'Pocono Mountains',
    'Chezzotel Pattaya': 'Pattaya',
    'Chi Heng B&B': 'Taiwan',
    'Chiaohsi Mediterranean Spa B&B': 'Yilan',
    'Chirping Hills Resort Bhimtal': 'Bhimtal',
    'Chirping Orchard, Mukteshwar': 'Mukteshwar',
    'ChongQing BackHome Riverview Hotel': 'Chongqing',
    'Chongqing Auwi Hotel': 'Chongqing',
    'Chongqing Dierui Hotel': 'Chongqing',
    'Chongqing Haoting Riverside Hotel': 'Chongqing',
    'Chongqing Jiefangbei Centre Bairui Hotel': 'Chongqing',
    'Chongqing Junsheng Cloud River View': 'Chongqing',
    'Chongqing Justom Hotel Branch 1': 'Chongqing',
    'Chongqing Justom Hotel Branch 2': 'Chongqing',
    'Chongqing Justom Hotel Branch 3': 'Chongqing',
    'Chongqing KaoYu Hotel': 'Chongqing',
    'Chongqing Lingdu Gaokong Jiangjing Hotel': 'Chongqing',
    'Chongqing Mansion Manyue Hotel': 'Chongqing',
    'Chongqing Sujiang Yunduan Riverview': 'Chongqing',
    'Chongqing Wuyu Shanxing Hotel': 'Chongqing',
    'Chongqing jiayu emperor hotel': 'Chongqing',
    'Chonor House': 'Dharamshala',
    'Chunda Haveli - A Boutique Hotel': 'Udaipur',
    'Churana Resort Motobu': 'Okinawa',
    'Citrus Grande Hotel Pattaya by Compass Hospitality': 'Pattaya',
    'Clarissa Resort Mukteshwar': 'Mukteshwar',
    'Clarks Inn Bhowali': 'Uttarakhand',
    'Clarks Inn Express Udaipur': 'Udaipur',
    'Classic Lodges Ramsey Park': 'Isle of Man',
    'Click Collection The Abode Dharamshala': 'Dharamshala',
    'Climax Berlin': 'Berlin',
    'CloudScape': 'Yilan',
    'Cloudotel Walking Street Pattaya': 'Pattaya',
    'Coal Creek Motel': 'Victoria',
    'Coco Beach Hotel Jomtien Pattaya': 'Pattaya',
    'Collection O 93028 Homestay Joglo Ibu': 'Yogyakarta',
    'Commodious Hotel Kupang': 'Kupang',
    'Coral Sea Beach & Aqua Park': 'Hurghada',
    'Country Holidays Himalayan View Cottages Mukteshwar': 'Mukteshwar',
    'Country View B&B': 'Yilan',
    'County Homes Munnar': 'Munnar',
    'Courtyard Seoul Botanic Park': 'Seoul',
    'Crocodile Kruger Safari Lodge': 'Kruger',
    'Cross Pattaya Pratamnak': 'Pattaya',
    "D'Charruas Cabañas Chajari": 'Chajarí',
    "D'Polo Club And Spa Resort, Dharamshala": 'Dharamshala',
    'DEL MAX resort Pattaya': 'Pattaya',
    'DEV BAGH LUXURIOUS PRIVATE SUITES': 'Udaipur',
    'DUPLICADO  - Holiday Inn Express Chongqing Ciqikou Ancient Town by IHG': 'Chongqing',
    'DUPLICADO Alassari Plantation': 'Bali',
    'DUPLICADO Ardency Inn by Park Tree Udaipur': 'Udaipur',
    'DUPLICADO Club Mahindra Munnar': 'Munnar',
    'DUPLICADO Fiesto Hotel and Suites Enugu': 'Enugu',
    'DUPLICADO Goroomgo Silver Tree inn Bhimtal': 'Bhimtal',
    'DUPLICADO Hotel Grand Bhagwat': 'India',
    'DUPLICADO Hotel Lakend': 'Udaipur',
    'DUPLICADO Hotel Le Ruchi the Prince': 'Udaipur',
    'DUPLICADO Hotel Les Champs Jiaosi': 'Yilan',
    'DUPLICADO JW Marriott Hotel Chongqing': 'Chongqing',
    'DUPLICADO KHAKHRI HAVELI - A Boutique Hotel': 'Udaipur',
    'DUPLICADO Kruger Maroela Lodge': 'Kruger',
    'DUPLICADO Mcsrh Hotel - Chongqing Jiefangbei Pedestrian Street': 'Chongqing',
    'DUPLICADO Modessa Island': 'Mindoro',
    'DUPLICADO Mulberry Araliayas Resort & Spa': 'Udaipur',
    'DUPLICADO Palace Inn Toyota': 'Toyota',
    'DUPLICADO ProfilHotels Halmstad Plaza': 'Halmstad',
    'DUPLICADO Pumphouse Point': 'Australia',
    'DUPLICADO Radisson Udaipur': 'Udaipur',
    'DUPLICADO Raffles Udaipur': 'Udaipur',
    'DUPLICADO Royal Cliff Beach Terrace Hotel Pattaya': 'Pattaya',
    'DUPLICADO Sayaji Resort and Spa Udaipur': 'Udaipur',
    'DUPLICADO Scenic, Munnar - IHCL SeleQtions': 'Munnar',
    'DUPLICADO Season Five Hotel': 'Pattaya',
    'DUPLICADO Tabist Shizukuishi Resort Hotel': 'Shizukuishi',
    'DUPLICADO The Leela Palace Udaipur': 'Udaipur',
    'DUPLICADO The Proud Hotel Pattaya': 'Pattaya',
    'DUPLICADO Toyota Prestige Hotel': 'Toyota',
    'DUPLICADO Tree of Life Amara Resorts & Spa Udaipur': 'Udaipur',
    'DUPLICADO Villa Oranje Pattaya': 'Pattaya',
    'DUPLICADO Zubani hotel and suites': 'Enugu',
    'DUPLICADO-Quality Inn Williston Area': 'North Dakota',
    'Dahabeya Queen Farida': 'Aswan',
    'Daiwa Roynet Hotel Sendai-nishiguchi PREMIER': 'Sendai',
    'DaiwaRoynetHotel Sendai Ichibanchou PREMIER': 'Sendai',
    'Daksh The Fateh Retreat - Udaipur': 'Udaipur',
    'Dani Beach Villa Penuktukan': 'Bali',
    'Dariva Place': 'Pattaya',
    'Darling Harbour Residence - Pattaya': 'Pattaya',
    'Dawy House': 'El Cairo',
    'Days Hotel by Wyndham Chongqing Kaichuang': 'Chongqing',
    'Days Inn by Wyndham Perrysburg/Toledo': 'Toledo',
    'DeeProm Pattaya Hotel': 'Pattaya',
    'Deep Blue Z10 Pattaya': 'Pattaya',
    'Dera Pichola A Lake Facing Hotel': 'Udaipur',
    'Desert Escape with Pool, Firepit, Putting Green': 'Coachella Valley',
    'Designer House': 'Yilan',
    'Devi Palace Monsoon Palace View Resort Udaipur': 'Udaipur',
    'Dharamkot Outlook': 'Dharamshala',
    'Diamond Hotel Ngapali': 'Ngapali Beach',
    'Divine Homes- Sattal By ASPL': 'Uttarakhand',
    'Dockside Guest Quarters & Restaurant': 'Maine',
    'Dolomia rosmini': 'Trento',
    'Dongshan River Left bank B&B': 'Yilan',
    'Dormy Inn Express Sendai Seaside': 'Sendai',
    'Dormy Inn Seoul Gangnam': 'Seoul',
    'Doubletree By Hilton Canakkale': 'Canakkale',
    'Dragon Beach Resort Jomtien Pattaya': 'Pattaya',
    'Dream Catcher Plantation Resort': 'Bali',
    'Dream of Africa Bush Lodge': 'Kruger',
    'Dreams Resort Udaipur': 'Udaipur',
    'EEC Home North Pattaya - Naklua': 'Pattaya',
    'ENJI S Shancheng Designer Hotel': 'Chongqing',
    'ENTRE VIÑEDOS RESORT HOTEL': 'Mendoza',
    'East Commercial Affairs Hotel': 'Luodong',
    'Eastiny Bella Vista Hotel': 'Pattaya',
    'Echarm PLUS Hotel Chongqing': 'Chongqing',
    'Echor Mandara Tree Villa Dharamshala': 'Dharamshala',
    'Eco Nubia Ecolodge': 'Aswan',
    'Elgalala Aqua Park': 'Aswan',
    'Emerald Woods Mukteshwar': 'Mukteshwar',
    'Enji M Hotel-Jiefangbei Hongyadong': 'Chongqing',
    'Essentia Udaipur Luxury Resort & Spa': 'Udaipur',
    'Eve Place Pattaya': 'Pattaya',
    'Evergreen Garden Home': 'Yilan',
    'Everhome Suites Corona': 'Los Angeles (and vicinity), CA, US',
    'Everyday Hot Spring Hotel': 'Yilan',
    'Excel Hotels & Resorts Bhimtal': 'Bhimtal',
    'Excel Hotels & Resorts Mall Road Nainital': 'Nainital',
    'Extended Stay Brunswick': 'Brunswick',
    'FX Hotel Pattaya': 'Pattaya',
    'FabExpress Mewar Shine': 'Udaipur',
    'Fairfield Inn & Suites by Marriott San Jose North/Silicon Valley': 'San Jose - Silicon Valley',
    'Fairfield by Marriott Goa Anjuna': 'Goa',
    'Fairmont Udaipur Palace': 'Udaipur',
    'Fairtex Express': 'Pattaya',
    'Fairtex Residence': 'Pattaya',
    'Fan Sea Resort Kohlarn': 'Pattaya',
    'Fateh Niwas': 'India',
    'Fateh Vilas by Fateh Collection': 'Udaipur',
    'Fiesto Continental Hotel Enugu': 'Enugu',
    'Fiesto Hotel and Suites Enugu': 'Enugu',
    'First Camp Tylösand': 'Halmstad',
    'Floral Hotel Chongqing Meila': 'Chongqing',
    'Four Points by Sheraton Chongqing': 'Chongqing',
    'Four Points by Sheraton Seoul, Guro': 'Seoul',
    'Fourium Pattaya Hotel and Serviced Residence': 'Pattaya',
    "Foxy Crocodile Bush Lodge & Kruger Safari's - No Loadshedding": 'Kruger',
    'Foxy Crocodile Bush Lodge & Kruger Safaris': 'Kruger',
    'Fresh Resort Pattaya': 'Pattaya',
    'Fukun 3 Motel': 'Taiwan',
    'Fukun 5 Motel': 'Taiwan',
    'Fukun Motel': 'Taiwan',
    'GLOUCESTER HOTEL CHEONGJU': 'Cheongju',
    'Galaxy Minyoun Chongqing Xiannv Mountain Resort': 'Chongqing',
    'Ganeshwaram Hotel & Restaurant Bhowali': 'Uttarakhand',
    'Garden Paradise Hotel & Serviced Apartment': 'Pattaya',
    'Garner Hotel Pattaya Central by IHG': 'Pattaya',
    'Garrya Bianti Yogyakarta': 'Yogyakarta',
    "Genie's Pattaya": 'Pattaya',
    'Ginger Udaipur Shastri Circle': 'Udaipur',
    'Gino House': 'Pattaya',
    'Gloria Aqua Park Hotel': 'Hurghada',
    'Go2bed Pattaya': 'Pattaya',
    'GoBravo 2BR Lux Villa wt Pvt Pool Udapur': 'Udaipur',
    'Golden Jomtien Beach Hotel': 'Pattaya',
    'Golden Star Pattaya': 'Pattaya',
    'Golden Tulip Pattaya Beach Resort': 'Pattaya',
    'Goroomgo Adhya Inn Bhimtal': 'Bhimtal',
    'Goroomgo Agnija Udaipur': 'Udaipur',
    'Goroomgo Anant Vilas Resort Bhimtal': 'Bhimtal',
    'Goroomgo Chinar Lake View Nainital': 'Nainital',
    'Goroomgo Colonel Cottage Lake View Nainital': 'Nainital',
    'Goroomgo Cottage Orchid Nainital': 'Nainital',
    'Goroomgo Deluxe Ankur Lake View Nainital': 'Nainital',
    'Goroomgo Dolls Inn Nainital': 'Nainital',
    'Goroomgo GP Mall Road Nainital': 'Nainital',
    'Goroomgo Golden Nest Nainital': 'Nainital',
    'Goroomgo Herb Club Homestay Bhimtal': 'Bhimtal',
    'Goroomgo Hotel Aqua Waterfall Dharamsala': 'Dharamshala',
    'Goroomgo Hotel Hill View Homes Bhimtal': 'Bhimtal',
    'Goroomgo Kanara Bhimtal': 'Bhimtal',
    'Goroomgo Lake View Mall Road Nainital': 'Nainital',
    'Goroomgo Lalghat Haveli Udaipur': 'Udaipur',
    'Goroomgo Long View Retreat Nainital': 'Nainital',
    'Goroomgo Moon Nainital': 'Nainital',
    'Goroomgo Morning Moon Bhimtal': 'Bhimtal',
    'Goroomgo New Bharat Nainital': 'Nainital',
    'Goroomgo Palm Bhimtal': 'Bhimtal',
    'Goroomgo Peace Space Resort Nainital': 'Nainital',
    'Goroomgo Portola Hotel By Parkside Dharamshala': 'Dharamshala',
    'Goroomgo Radha Continental Nainital': 'Nainital',
    'Goroomgo Rajpal Palace Udaipur': 'Udaipur',
    'Goroomgo Rani Palace Udaipur': 'Udaipur',
    'Goroomgo Sai Sadan Cottage Nainital': 'Nainital',
    'Goroomgo Sapphire Inn Bhimtal': 'Bhimtal',
    'Goroomgo Shah Guest House Nainital': 'Nainital',
    'Goroomgo Silver Tree inn Bhimtal': 'Bhimtal',
    'Goroomgo The Sojourn, Adharshila & Gulmohar Cottages Dharamsala': 'Dharamshala',
    'Goroomgo UK Homestay Nainital': 'Nainital',
    'Goroomgo You and Me Mallital Nainital': 'Nainital',
    'Grand Allevia Villa': 'Bali',
    'Grand Continent- A Luxury Collection Udaipur': 'Udaipur',
    'Grand Hotel Prius - Adults Only': 'Pattaya',
    'Grand Kruger Lodge and Spa': 'Kruger',
    'Grand Residence Jomtien': 'Pattaya',
    'Grande Centre Point Pattaya': 'Pattaya',
    'Grande Centre Point Space Pattaya': 'Pattaya',
    'Grande Classic Pattaya': 'Pattaya',
    'Grant Village - Inside the Park': 'Yellowstone',
    'Green Forest Villa': 'Bali',
    'Green Roof Hotel Nainital': 'Nainital',
    'Grha Awen Sleman': 'Yogyakarta',
    "Griya D'Carik": 'Yogyakarta',
    'Griya Godean Syariah Yogyakarta': 'Yogyakarta',
    'Griya Joglo Kaliurang': 'Yogyakarta',
    'Griya Misty': 'Yogyakarta',
    'Gu-Ji Gu-Ji Garden B&B': 'Luodong',
    'H Avenue Hotel Idae Sinchon': 'Seoul',
    'HBC Grand Himalayan Hotel & Resort': 'India',
    'HOTEL ALPE BELLARIA': 'Rimini',
    'HOTEL ARAWALI UDAIPUR CITY': 'Udaipur',
    'HOTEL Churabeach': 'Okinawa',
    'HOTEL LiVEMAX Aichi Toyota-Ekimae': 'Toyota',
    'HOTEL LiVEMAX SENDAI AOBADORI': 'Sendai',
    'HOTEL LiVEMAX SENDAI KOKUBUNCHO': 'Sendai',
    'HOTEL MAHENDRA PRAKASH': 'Udaipur',
    'HOUSE HOTEL Central Pattaya': 'Pattaya',
    'HOUSE HOTEL Walking Street Pattaya': 'Pattaya',
    'HUALUXE Chongqing Science Hall by IHG': 'Chongqing',
    'Halmstad Golfarena Hotell': 'Halmstad',
    'Halmstad Gårdshotell': 'Halmstad',
    'Halmstad Hotell & Vandrarhem Kaptenshamn': 'Halmstad',
    'Halo Sea Kohlarn': 'Pattaya',
    'Hamiltons Lodge And Restaurant Malelane': 'Kruger',
    'Hampton Inn & Suites Corona, Ca': 'Los Angeles (and vicinity), CA, US',
    'Happy Bou Jomtien Guesthouse': 'Pattaya',
    'Har Niwas': 'India',
    'Hareya Ryokan': 'Japan',
    'Hartola Panorama Cottage': 'Uttarakhand',
    'Has Pattaya': 'Pattaya',
    'Heidenauer Hotel im Park': 'Dresden',
    'Henn na Hotel Premier Sendai Kokubuncho': 'Sendai',
    'Heritage Hotel Raznjevica Dvori': 'Serbia',
    'Hermann Hotel Pattaya': 'Pattaya',
    'Hide-in Udaipur': 'Udaipur',
    'High Sky Resort - Best Luxury Hotel in Dharamkot': 'Dharamshala',
    'Hilton Club The Beach Resort Sesoko': 'Okinawa',
    'Hilton Goa Resort Candolim': 'Goa',
    'Hilton Okinawa Sesoko Resort': 'Okinawa',
    'Himaaksh cottages sigri': 'Uttarakhand',
    'Himalayan Horizon and Cafe': 'India',
    'Himalayan Inn': 'India',
    'Himalayan Off Trails': 'India',
    'Himalayan Serenity': 'India',
    'Historic Farmhouse in Hohnebostel With Garden Near Lake': 'Hannover',
    'Holiday Heaven Munnar': 'Munnar',
    'Holiday Inn Chongqing Science Hall by IHG': 'Chongqing',
    'Holiday Inn Chongqing Shuangfu by IHG': 'Chongqing',
    'Holiday Inn Chongqing Yungang': 'Chongqing',
    'Holiday Inn Express & Suites Bengaluru Old Madras': 'Bengaluru',
    'Holiday Inn Express & Suites Bengaluru Old Madras Road by IHG': 'Bengaluru',
    'Holiday Inn Express Chongqing Central Park by IHG': 'Chongqing',
    'Holiday Inn Express Chongqing Ciqikou Ancient Town by IHG': 'Chongqing',
    'Holiday Inn Express Chongqing Tongliang by IHG': 'Chongqing',
    'Holiday Inn Express Hamburg South A7 AS42 by IHG': 'Hamburg',
    'Holiday Inn Express Hongdae Seoul': 'Seoul',
    'Holiday Inn Express Langfang Yanjiao by IHG': 'Langfang',
    'Holiday Inn Hotel and Suites Chongqing Nanan by IHG': 'Chongqing',
    'Holiday Inn La Verkin Zion Park by IHG': 'Zion',
    'Home of 120 B&B': 'Yilan',
    'Homestay Damandiri Prambanan Syariah': 'Yogyakarta',
    'Homewood Suites By Hilton Fremont, Ca': 'San Jose - Silicon Valley',
    'Honeysuckle Family Castle': 'Yilan',
    'Hoshino Resorts KAI Akiu': 'Japan',
    'Hosteria y Cabañas Posada Quinen by Nordic': 'Neuquén',
    'Hotal Devraj Niwas on Lake Pichola Udaipur': 'Udaipur',
    'Hotel & Spa TOPOS Sendai Station - Caters to Men': 'Sendai',
    "Hotel 360 By D'Polo Dharamshala": 'Dharamshala',
    'Hotel Akash - Luxury Hotel In Mcleodganj': 'Dharamshala',
    'Hotel Alpha-One Otsu': 'Otsu',
    'Hotel Amazing Udaipur by Heritage inn': 'Udaipur',
    'Hotel Amber Pattaya': 'Pattaya',
    'Hotel Amet Haveli': 'Udaipur',
    'Hotel Apni Haveli Villa': 'Udaipur',
    'Hotel Apricot One Udaipur -Near Fateh Sagar Lake': 'Udaipur',
    'Hotel Aroma Nainital': 'Nainital',
    'Hotel Asian Plaza Dharamshala': 'Dharamshala',
    'Hotel Astor Piacenza': 'Piacenza',
    'Hotel Atlantis Otsu - Adults Only': 'Otsu',
    'Hotel Avon Lake View Mall Road Nainital': 'Nainital',
    'Hotel Biwako Cerisaie': 'Japan',
    'Hotel Biz Suwon': 'Suwon',
    'Hotel Broadway Udaipur': 'Udaipur',
    'Hotel Buddha House Himalayan Brothers': 'India',
    "Hotel Buddha's Abode- Best Hotel in McleodGanj Main Market": 'Dharamshala',
    'Hotel Calangute Central': 'Goa',
    'Hotel Cappuccino': 'Seoul',
    'Hotel Chinar Lake View Near Mall Road': 'Nainital',
    'Hotel City Express By Downtown Udaipur': 'Udaipur',
    'Hotel Clear Sky Udaipur': 'Udaipur',
    'Hotel Clover': 'Singapur',
    'Hotel Continental Relax Spa, BW Signature Collection': 'Hotel Continental Relax Spa',
    'Hotel Crown Hills Sendai Aobadori': 'Sendai',
    'Hotel Darbargarh, Udaipur': 'Udaipur',
    'Hotel Deep Palace Near Bus Stand Udaipole': 'Udaipur',
    'Hotel Deluxe Ankur Lake View Mall Road Nainital Near Naina Devi Temple': 'Nainital',
    'Hotel Denim Seoul': 'Seoul',
    'Hotel Dharamshala Ayush Health Paradise': 'Dharamshala',
    'Hotel Dream villa udaipur': 'Udaipur',
    'Hotel Flatties Mall Road Nainital': 'Nainital',
    'Hotel Grand Bach Sendai': 'Sendai',
    'Hotel Grand Bhagwat': 'India',
    'Hotel Grand Terrace Sendai Kokubuncho': 'Sendai',
    'Hotel Green Arbor': 'Japan',
    'Hotel Green Pacific': 'Japan',
    'Hotel Green Park': 'Hyderabad',
    'Hotel Green Park Udaipur': 'Hyderabad',
    'Hotel Green With': 'Japan',
    'Hotel Hanuman Ghat': 'Varanasi',
    'Hotel Haridas Haveli Udaipur': 'Udaipur',
    'Hotel Harmony Blue Mcleodganj, Dharamshala': 'Dharamshala',
    'Hotel Heritage haveli': 'Udaipur',
    'Hotel Hill view by Heritage inn Udaipur': 'Udaipur',
    'Hotel Hillora Mcleodganj': 'Dharamshala',
    'Hotel Hof Sudermühlen': 'Egestorf',
    'Hotel Imperial Udaipur': 'Udaipur',
    'Hotel Indigo Bali Seminyak Beach by IHG': 'Bali',
    'Hotel Isenbütteler Hof': 'Wolfsburg',
    'Hotel JK Dharamshala': 'Dharamshala',
    'Hotel Jagati Niwas Near Mall Road': 'India',
    'Hotel Johzenji': 'Chongqing',
    'Hotel KGN Guest House Nainital Near Mall Road and Lake': 'Nainital',
    'Hotel Kale 17': 'Canakkale',
    'Hotel Kanak Niwas': 'India',
    'Hotel Keihan Sendai': 'Sendai',
    'Hotel Koo OotsuHyakucho': 'Otsu',
    'Hotel LaCalme Sendai - Adults Only': 'Sendai',
    'Hotel Label': 'Osaka',
    'Hotel Lakend': 'Udaipur',
    'Hotel Les Champs Jiaosi': 'Yilan',
    'Hotel Livemax Sendai Hirose-dori': 'Sendai',
    'Hotel Lotus Otsu  - Adults Only': 'Otsu',
    'Hotel Lotus morioka - Adult Only': 'Japan',
    'Hotel Luna Otsu': 'Otsu',
    'Hotel Mandovin - A Premium Hotel In Udaipur': 'Udaipur',
    'Hotel Manu Seoul': 'Seoul',
    'Hotel Manuni Inn Dharamshala': 'Dharamshala',
    'Hotel Matsukaze': 'Japan',
    'Hotel Meenakshi Udaipur': 'Udaipur',
    'Hotel Metropolitan Sendai East': 'Sendai',
    'Hotel Mewar Mahal - Udaipur': 'Udaipur',
    'Hotel Mewar Shine': 'Udaipur',
    'Hotel Mewarts Udaipur': 'Udaipur',
    'Hotel Mid Town Nainital Near Mall Road': 'Nainital',
    'Hotel Mirador de Barcia': 'Galicia',
    'Hotel Moon Nainital Near Mall Road Lake': 'Nainital',
    'Hotel Mumbai House Express': 'Mumbai',
    'Hotel My New Lovina': 'Bali',
    'Hotel NEO Eltari Kupang by Aston': 'Kupang',
    'Hotel Naddi Heights': 'Dharamshala',
    'Hotel Naru Seoul - MGallery Collection': 'Seoul',
    'Hotel Neelam Raj Nainital': 'Nainital',
    "Hotel O Am'key Villa Tretes 1": 'Surabaya',
    'Hotel O Amor Kost': 'Yogyakarta',
    'Hotel O Griya Estu Wening': 'Yogyakarta',
    'Hotel O Hepi Bungalow Lovina': 'Bali',
    'Hotel O Kaliurang Near Gunung Merapi Kaliurang': 'Yogyakarta',
    'Hotel O Kost Esklusif Barokah': 'Yogyakarta',
    'Hotel O Near Tugu Yogyakarta 2 formerly Monjali Inn': 'Yogyakarta',
    'Hotel O Pondok Wisata Sri MulyoNearSultan Agung Stadium Bantul': 'Yogyakarta',
    'Hotel O Sleman Near Bandara Adi Sutjipto Formerly Joglo Sorogenen': 'Yogyakarta',
    'Hotel O Wisma Harapan Baik': 'Yogyakarta',
    'Hotel O Yogyakarta near MM UGM formerly Bama Guesthouse': 'Yogyakarta',
    'Hotel O near Plaza Ambarrukmo Yogyakarta formerly Wisma Arya 2': 'Yogyakarta',
    'Hotel PIN Jiaoxi': 'Yilan',
    'Hotel PORTO TARA': 'Montenegro',
    'Hotel Palace Sendai': 'Sendai',
    'Hotel Pangot Himalayan View': 'India',
    'Hotel Panna Vilas Palace': 'Udaipur',
    'Hotel Paramount Udaipur': 'Udaipur',
    'Hotel Paras Mahal': 'India',
    'Hotel Premium Green Plus': 'Japan',
    'Hotel Premium Green Sovereign': 'Japan',
    'Hotel Raj Kuber': 'India',
    'Hotel Raj Niwas': 'India',
    'Hotel Ram Niwas': 'India',
    'Hotel Ramnivas Hotel-Restaurant Udaipur': 'Udaipur',
    'Hotel Relax Max Sariyatal Nainital': 'Nainital',
    'Hotel Royal Palm - A Budget Hotel in Udaipur': 'Udaipur',
    'Hotel Rühen, 24 Stunden Check in, kostenfreie Parkplätze': 'Wolfsburg',
    'Hotel STIPRAM Kaliurang Yogyakarta': 'Yogyakarta',
    "Hotel Saheb's Castle - Best Mountain View & Jacuzzi Suites, McLeodganj": 'Dharamshala',
    'Hotel Samdupling Himalayan Brothers': 'India',
    'Hotel Sangita Lake View Nainital': 'Nainital',
    'Hotel Sardus Pater': 'Sardinia',
    'Hotel Shah Guest House Nainital': 'Nainital',
    'Hotel Shiv Sagar Haveli Udaipur': 'Udaipur',
    'Hotel Shree Khodiyar By Rangoli Udaipur': 'Udaipur',
    'Hotel Shree Udai Vilas': 'Udaipur',
    'Hotel Sky Bhagsu': 'Dharamshala',
    'Hotel Sparrow Dharamshala': 'Dharamshala',
    'Hotel Square Ansan': 'Ansan',
    "Hotel Square One By D'Polo Dharamshala  ID 92552899": 'Dharamshala',
    'Hotel Star Inn Near Mall Road Nainital': 'Nainital',
    'Hotel Stern Pattaya': 'Pattaya',
    'Hotel Sunflower': 'Udaipur',
    'Hotel Sunrise Palace Udaipur': 'Udaipur',
    'Hotel Sunshine Dharamshala': 'Dharamshala',
    'Hotel Tara Bar & Resto Air Sanih': 'Bali',
    'Hotel Thamla Haveli': 'Udaipur',
    'Hotel The Tiger': 'Udaipur',
    'Hotel Townhouse @Udaipur City Railway Station': 'Udaipur',
    'Hotel Transit Pasuruan': 'Surabaya',
    'Hotel U Connect Near RTO Office, Udaipur': 'Udaipur',
    'Hotel Udai Palace': 'Udaipur',
    'Hotel Udaipur Stay': 'Udaipur',
    'Hotel Valletta': 'Yilan',
    'Hotel Vinayak Nainital': 'Nainital',
    'Hotel Vista Sendai': 'Sendai',
    'Hotel WD': 'Seoul',
    'Hotel Weingut Dehren': 'Ellenz-Poltersdorf',
    'Hotel Yaja Cheongju Terminal Branch': 'Cheongju',
    'Hotel Yaja Suwon City Hall': 'Suwon',
    'Hotel Zlatibor': 'Serbia',
    'Hotel ab Shiga': 'Japan',
    'Hotel mountain palace Udaipur': 'Udaipur',
    'Hotel Ávila Centro': 'Ávila',
    'Hotel&Ristorante Sicilia': 'Sicilia',
    'Hotelette Seoul Station': 'Seoul',
    'Hotell Toftalund AB': 'Dinamarca',
    'House of Trento - NO Reception': 'Trento',
    'Howard Johnson by Wyndham Pattaya JC': 'Pattaya',
    'Hyatt Place Melbourne, Essendon Fields': 'Australia',
    'Hótel Skálholt': 'Islandia',
    'INDITION Chongqing Jiangbeizui Financial': 'Chongqing',
    'INDITION Chongqing Jiefangbei Raffles': 'Chongqing',
    'IP Plus Pool Villa Pattaya': 'Pattaya',
    'Ice Inn Hotel Pattaya': 'Pattaya',
    'Imbube Safari Lodge': 'Kruger',
    'Inase Otsu Machiya Bed & Breakfast': 'Otsu',
    'Incredible Stay at Water Side El Gouna': 'El Gouna',
    'Inda Haveli': 'Udaipur',
    'Indaba Hotel Sasolburg': 'Sudáfrica',
    'India Hotel - Mall Road Nainital - Lake View': 'Nainital',
    'Indra Niwas': 'India',
    'Indulge Udaipur by PACK': 'Udaipur',
    'Infinity Sky 2.0 Jomtien Beach': 'Pattaya',
    'Injoy Hotel Halmstad': 'Halmstad',
    'InterContinental Pattaya Resort, an IHG Hotel': 'Pattaya',
    'Intersur Hotel La Cumbre': 'La Cumbre',
    'Issmy Hotel Spring Resort': 'Yilan',
    'J Inspired Hotel Pattaya': 'Pattaya',
    'JP Inn Pattaya': 'Pattaya',
    'Jajora Udaipur By Premier Hotels': 'Udaipur',
    'Janak Niwas': 'India',
    'Jean Boutique Pattaya': 'Pattaya',
    'Jiaoxi 320 B&B': 'Yilan',
    'Jinchuan Hotel': 'Japan',
    'Jinke Grand Hotel Chongqing': 'Chongqing',
    'Jomtien Beach Market Hotel': 'Pattaya',
    'Jomtien Beach SLEEP INN': 'Pattaya',
    'Jomtien Hisotel': 'Pattaya',
    'Jomtien Wave Residence': 'Pattaya',
    'Just Sleep Hotel Ansan Gojan Branch': 'Ansan',
    'Justa Ssatva Resort, Udaipur': 'Udaipur',
    'K2 Seaside Suites': 'Pattaya',
    'K2 Xanadu Pool Villa': 'Pattaya',
    'KANER BAGH A HERITAGE BOUTIQUE HOTEL': 'Udaipur',
    'KANKARWA HAVELI': 'Udaipur',
    'KHAKHRI HAVELI - A Boutique Hotel': 'Udaipur',
    'KJS Pattaya\u200b': 'Pattaya',
    'KKR Hotel Biwako': 'Japan',
    'KKinn South Pattaya Hotel': 'Pattaya',
    'KOKO HOTEL Sendai Station South': 'Sendai',
    'KOKO HOTEL Sendai Station West': 'Sendai',
    'Kafal Pako Resort – Himalayan View Resort In Mukteshwar': 'Mukteshwar',
    'Kagaribi No Yu Ryokusuitei': 'Japan',
    'Kai Cheng Inn': 'Yilan',
    'Kaladwas Lal Haveli': 'Udaipur',
    'Kalpić Suites & Villa': 'Croacia',
    'Kamalan Home': 'Taiwan',
    'Kambaku River Lodge': 'Kruger',
    'Kangen Boutique Hotel': 'Bali',
    'Kann Pattaya Hotel': 'Pattaya',
    'Kastel Pattaya Hotel': 'Pattaya',
    'Katson Castle Dharamshala': 'Dharamshala',
    'Kavacik Asia Hotel': 'Istanbul',
    'Kavish Holiday Hill Resort': 'India',
    'Kelapa Lovina Beach Villas': 'Bali',
    'Keys Select by Lemon Tree Hotels Udaipur': 'Udaipur',
    'Khas Mahal by Fateh Collection': 'Udaipur',
    'Kieng Talay Studio by PSR': 'Pattaya',
    'Kingdom Love Bed and Breakfast': 'Yilan',
    'Kintsugi at Rangniwas': 'India',
    'Kispet Konak Hotel': 'Istanbul',
    'Klein Heidelberg': 'Pattaya',
    'Koenig Hotel Pattaya': 'Pattaya',
    'Koh Larn De Beach': 'Pattaya',
    'Koh Larn FC': 'Pattaya',
    'Koh Larn Riviera': 'Pattaya',
    'Kokotel Pattaya North Beach': 'Pattaya',
    'Kosciuszko Tourist Park': 'Australia',
    'Kotra Haveli A Boutique Hotel By The Lake Pichola': 'Udaipur',
    'Kruger Inn Backpackers': 'Kruger',
    'Kruger Maroela Lodge': 'Kruger',
    'Kruger Riverside Lodge': 'Kruger',
    'Kruger View Chalets': 'Kruger',
    'Kudrat Resort and Suites Jim Corbett': 'Jim Corbett',
    'Kyaw Ngapali Lodge': 'Ngapali Beach',
    'Kyou Bar Lounge & Inn': 'Sendai',
    "L'Escape Hotel": 'Seoul',
    'L7 HONGDAE by LOTTE HOTELS': 'Seoul',
    'LEK Jomtien Hotel': 'Pattaya',
    'LK Celestite': 'Pattaya',
    'LK Crystal Ville Pattaya': 'Pattaya',
    'LK Emerald Beach': 'Pattaya',
    'LK Majestic Villa': 'Pattaya',
    'LK President': 'Pattaya',
    'La Casa Pattaya': 'Pattaya',
    'La Santir by PSR': 'Pattaya',
    'Lafayette Boutique Hotel Yogyakarta': 'Yogyakarta',
    'Lagoon Ngapali Beach Lodge': 'Ngapali Beach',
    'Laguna House': 'Montenegro',
    'Lake Lodge Cabins - Inside the Park': 'Glacier National Park',
    'Lake McDonald Lodge - Inside the Park': 'Glacier National Park',
    'Lakeshore Hotel Suao': 'Yilan',
    'Lakeshore Hotel Yilan': 'Yilan',
    'Lala Villa Kohlarn': 'Pattaya',
    'Landgasthof Wickert': 'Mörsdorf',
    'Lanna Hotel by Kasalong Resort and Spa Pattaya': 'Pattaya',
    'Lanyan Homestay': 'Yilan',
    'Lawinta Hotel Pattaya': 'Pattaya',
    'Lawrence Solitaire Resort Nainital': 'Nainital',
    'Le Bali Resort': 'Bali',
    'Le Chateau Lambousa Hotel': 'Chipre',
    'Le Meridien Goa': 'Goa',
    'Le Nara Residence': 'Pattaya',
    'Le Prive Resort': 'India',
    'Lemon Tree Hotel Anjuna Goa': 'Goa',
    'Lemon Tree Hotel Mcleodganj': 'Dharamshala',
    'Lemon Tree Hotel Mukteshwar': 'Mukteshwar',
    "Let's Hyde Pattaya Resort & Villas": 'Pattaya',
    'Letsatsing Lodge': 'Sudáfrica',
    'Levana Pattaya Hotel': 'Pattaya',
    'Lewit Hotel Pattaya, a member of Radisson Individuals': 'Pattaya',
    'Lian Yuan B&B': 'Yilan',
    'Lido Beach Hotel Pattaya': 'Pattaya',
    'Lill sparrow by The Verdant Escapes': 'Uttarakhand',
    'Little Heave Nainita Uttarakhand': 'Nainital',
    'Little Mastiff Dharamshala Airport': 'Dharamshala',
    'Live for you B&B': 'Yilan',
    'LiveAway Mukteshwar by PACK': 'Mukteshwar',
    'LiveAway Ramgarh by PACK': 'Uttarakhand',
    'Lords Inn Udaipur': 'Udaipur',
    'Lotusland Resort': 'Bali',
    'Lovina Beach Club & Resort': 'Bali',
    'Lovina Haven Boutique Resort': 'Bali',
    'Lovina Loca': 'Bali',
    'Lovina Oasis': 'Bali',
    'Lovinalife Room & Cafe': 'Bali',
    'M CASA HOTEL PATTAYA': 'Pattaya',
    'M Pattaya Hotel': 'Pattaya',
    'M Place Pattaya': 'Pattaya',
    'MClub Del Golfo': 'Mallorca Island',
    'MIDO HOTEL PATTAYA': 'Pattaya',
    'Ma-Blue Garden House': 'Japan',
    'Maa Bhagwati Homestay & Restro': 'India',
    'Maan Vilas By Stone Wood Udaipur': 'Udaipur',
    'Madri Haveli Retreat': 'Udaipur',
    'Magnifico INN Pattaya': 'Pattaya',
    'Mahua Monks -Villa Resort Udaipur': 'Udaipur',
    'Maiyue Hotel-Chongqing Jiefangbei': 'Chongqing',
    'Mamori House at Koh Larn': 'Pattaya',
    'Mandarin Eastville, Pattaya': 'Pattaya',
    'Manuscript- Jhilwara Haveli': 'Udaipur',
    'Marble Garden View Pattaya': 'Pattaya',
    'March Hotel Pattaya': 'Pattaya',
    'Marina Jomtien Beach': 'Pattaya',
    'Marina Villa 1': 'Pattaya',
    'Marina x InfinitySky': 'Pattaya',
    'Marine Beach Hotel Pattaya': 'Pattaya',
    'Marine Plaza Hotel Pattaya': 'Pattaya',
    'Marine Yensabai Hotel Pattaya': 'Pattaya',
    'Massarossa Pool Villa Pattaya': 'Pattaya',
    'Mastiff Select Mandavya Dharamkot, McLeodganj': 'Dharamshala',
    'Matcha House Jomtien Pattaya': 'Pattaya',
    'Mavilla Hotel': 'Istanbul',
    'Mayhill Hotel': 'Gales',
    'Mazrika Sesoko': 'Okinawa',
    'Mcsrh Hotel - Chongqing Jiefangbei Pedestrian Street': 'Chongqing',
    'Mcsrh Hotel -Chongqing Chaotianmen': 'Chongqing',
    'Mcsrh Hotel -Chongqing Guanyinqiao': 'Chongqing',
    'Mcsrh Hotel -Chongqing Shibati': 'Chongqing',
    'Medalio Resort Udaipur Shobhagpura': 'Udaipur',
    'Mehood Lestie International Hotel Chongqing Yuzhong Lianglukou Metro Branch': 'Chongqing',
    'Meitetsu Toyota Hotel': 'Toyota',
    'Melia Chongqing': 'Chongqing',
    'Mementos By ITC Hotels Ekaaya Udaipur': 'Udaipur',
    'Mera Mare Pattaya': 'Pattaya',
    'Mercure Ambassador Seoul Hongdae': 'Seoul',
    'Mercure Ambassador Seoul Magok': 'Seoul',
    'Mercure Rayong Lomtalay Villas & Resort': 'Rayong',
    'Merica Hotel -Chongqing Guanyinqiao': 'Chongqing',
    'Merica Hotel -Chongqing Jiefangbei': 'Chongqing',
    'Mermaid Beach Resort': 'Pattaya',
    'Mewar Haveli': 'Udaipur',
    'Mewar Palace Resort & Spa': 'Udaipur',
    'Mewar palace resort and spa': 'Udaipur',
    'Mgh 114 Hotel Krishna Udaipur': 'Udaipur',
    'Milan Yilan': 'Yilan',
    'Mild Life Hostel Udaipur': 'Udaipur',
    'Mimpi Nyata Villa & Dive Center': 'Bali',
    'Mind Tourist Hotel': 'Seoul',
    'Modernbright Service Apartment': 'Laem Chabang',
    'Modessa Island': 'Mindoro',
    'Mondrian Seoul Itaewon': 'Seoul',
    'Mont Talay Hotel': 'Pattaya',
    'Mountain bnb hartola Uttarakhand': 'Uttarakhand',
    'Moustache Bhimtal Luxuria, Nainital': 'Bhimtal',
    'Moustache Select Mukteshwar': 'Mukteshwar',
    'Moustache Select Nainital': 'Nainital',
    'Moustache Select Udaipur': 'Udaipur',
    'Moustache Udaipur Luxuria': 'Udaipur',
    'Moustache Udaipur Verandah': 'Udaipur',
    'Mu Jiao Xi Hotel': 'Yilan',
    'Mulberry Araliayas Resort & Spa': 'Udaipur',
    'Munnar Jungle Camp': 'Munnar',
    'Mushroom House Kohlarn': 'Pattaya',
    'My Downtown - Prime A Premium Boutique Hotel Udaipur': 'Udaipur',
    'My Downtown - The Red Pier': 'India',
    'Mystical Valley View Resort and Spa, Udaipur': 'Udaipur',
    'Mytt Hotel Pattaya': 'Pattaya',
    'Mövenpick Siam Na Jomtien Pattaya': 'Pattaya',
    'NOA HOTEL Toyotaminami - Adults Only': 'Toyota',
    'NUB INN': 'Aswan',
    'Naini Jungle Retreat By Tag Resorts': 'Nainital',
    'Nainital Hotel C Residency': 'Nainital',
    'Nainital Hotel Chand Regency': 'Nainital',
    'Nainital Hotel R C Near mall Road': 'Nainital',
    'Nainital Hotel Sunset': 'Nainital',
    'Nalanta Pattaya Hotel': 'Pattaya',
    'Narayans Leela Inn By SGOH': 'India',
    'Navana Nature Escape': 'Darjeeling',
    'Neat House Hongdae': 'Seoul',
    'Neelesh Inn - Luxury Lake View Hotel With Swimming Pool On Bhimtal Lake': 'Bhimtal',
    'Neev Haveli': 'Udaipur',
    'Nestonature Glamping Dharamshala': 'Dharamshala',
    'Netley Hall': 'Southampton',
    'New Armadale Nainital': 'Nainital',
    'New Pind Balluchi Inn': 'India',
    'Newel Psychiko': 'Athens',
    'Newvera Tourist Hotel': 'Seoul',
    'Nexottel Shree Nanda': 'Udaipur',
    'Ngapali Paradise Hotel': 'Ngapali Beach',
    'Ngapali Win Hotel': 'Ngapali Beach',
    'Nglaras Resort Yogyakarta': 'Yogyakarta',
    'Niccolo Chongqing': 'Chongqing',
    'Nice Resort Pattaya': 'Pattaya',
    'Nightcap at Empire Hotel': 'Australia',
    'Nine Brick Hotel': 'Seoul',
    'Nine Rooms Trento': 'Trento',
    'Nine Star Hotel Sinchon': 'Seoul',
    'Nong Apartment Pattaya - Adults Only': 'Pattaya',
    'Nonze Hostel': 'Pattaya',
    'Norbu The Montanna, Dharamshala - IHCL SeleQtions': 'Dharamshala',
    'North Europe Holiday House': 'Yilan',
    'North Wing Canggu Resort': 'Bali',
    'NorthPoint Pattaya with Sea View': 'Pattaya',
    'Novotel Ambassador Seoul Yongsan - Seoul Dragon City': 'Seoul',
    'Novotel Lubumbashi': 'Lubumbashi',
    'Novotel Sydney Cabramatta': 'Australia',
    'Nubateera': 'Aswan',
    'Nukkad Guest House Near Lake Pichola': 'Udaipur',
    'O-Bay Design HotelPrachuap': 'Prachuap Khiri Khan',
    'OMEO Clearlake Oaks': 'California',
    'OTC By 4 Lal Ghat - My Downtown Hotels': 'Udaipur',
    'OYO 10319 Hotel Pichola Haveli': 'Udaipur',
    'OYO 143 Dday Resotel Pattaya Hotel': 'Pattaya',
    'OYO 145 Pattaya Bed Boutique': 'Pattaya',
    'OYO 2896 Uma Menuh Guest House Near Pantai Keramas': 'Bali',
    'OYO 520 Pattaya Cantina': 'Pattaya',
    'OYO 698 Pattaya City': 'Pattaya',
    'OYO 75486 Anna Residence Jomtien': 'Pattaya',
    'OYO 824 Valida Resort': 'Pattaya',
    'OYO 830 Kohlarn Mountain': 'Pattaya',
    'OYO 917 PK Residence Pattaya': 'Pattaya',
    'OYO 93482 Penginapan Tenang Lovina': 'Bali',
    'OYO Life  92953 Nirmala Kost': 'Yogyakarta',
    'OYO Life 91239 Kost Rosandy House Yogyakarta': 'Yogyakarta',
    'OYO Life 92087 Griya Nurainy': 'Yogyakarta',
    'OYO Life 92838 Kost Ibu Surya': 'Yogyakarta',
    'OYO Life 92954 Shanti Kost': 'Yogyakarta',
    'OYO The Hillside Hotel': 'Hillside',
    'OZO North Pattaya': 'Pattaya',
    'Ocean Ngapali Lodge': 'Ngapali Beach',
    'Ocean Paradise Bali': 'Bali',
    'Ocean View House Churaumi': 'Okinawa',
    'Oladar Haveli – My Downtown Hotels': 'Udaipur',
    'Old Faithful Inn - Inside the Park': 'Yellowstone',
    'Olympia Hotel at Capitol Lake': 'Olympia',
    'Omah Demak Ijo By Occupied': 'Yogyakarta',
    'Omah Kloewoeng Resort Kaliurang': 'Yogyakarta',
    'Omunity Bali': 'Bali',
    'One Fukun Hotel': 'Taiwan',
    'One Myanmar Resort Ngapali': 'Ngapali Beach',
    'One Patio Hotel Pattaya': 'Pattaya',
    'Onsen Guesthouse Sakaeya': 'Japan',
    'Onsense Villa': 'Japan',
    'Onyado Nono Sendai Hot Spring': 'Sendai',
    'Ooedo Onsen Monogatari Premium Sendai Sakunami': 'Sendai',
    'Opal Motel': 'Australia',
    'Opal Private Nubian Hotel': 'Aswan',
    'Orange Inn Sendaihigashi': 'Sendai',
    'Orient Luxury Hotel-Jiao Xi': 'Yilan',
    'Orion International North of Chongqing': 'Chongqing',
    'P-Park Hotel Pattaya': 'Pattaya',
    'PACK Mukteshwar': 'Mukteshwar',
    'PETAL OF MEWAR - A Luxury Boutique Hotel': 'Udaipur',
    'PUERTO LACAR LODGE SMARG': 'San Martín de los Andes',
    'Paandora Grand Udaipur': 'Udaipur',
    'Padmasari Resort Hotel': 'Bali',
    'Pagoda Hotel Chongqing INCITY Hualongqiao Station': 'Chongqing',
    'Pagoda Hotel Chongqing Jiefangbei': 'Chongqing',
    'Pagoda Hotel Of SSAW ChongQing International Land-sea': 'Chongqing',
    'Palace Inn Toyota': 'Toyota',
    'Palm Beach Villas Bali': 'Bali',
    'Pandawa Village': 'Bali',
    'Pande Guest House Pemuteran': 'Bali',
    'Pansal Kothi A boutique Hotel': 'Udaipur',
    'Paradise Park Jomtien by PSR ASIA': 'Pattaya',
    'Parallel Hotel Udaipur, a member of Radisson Individuals': 'Udaipur',
    'Parijat Private Pool Villa 1, 2 and 3 BHK': 'Udaipur',
    'Parinya Hill Homestay & Cafe Koh Larn': 'Pattaya',
    "Parinya's Apartment": 'Pattaya',
    'Parion Hotel': 'Canakkale',
    'Parion House Hotel': 'Canakkale',
    'Park Avenue': 'Seoul',
    'Pass Happiness On': 'Yilan',
    'Pattaya Bed Boutique Sha': 'Pattaya',
    'Pattaya Charm': 'Pattaya',
    'Pattaya Park Beach Resort': 'Pattaya',
    'Pattaya at Nine': 'Pattaya',
    'Pavilion Farmstay Udaipur': 'Udaipur',
    'Pax Gk Confier Dharamshala': 'Dharamshala',
    'Pax Grand Blue Udaipur': 'Udaipur',
    'Pax Rafahiya Haveli Udaipur': 'Udaipur',
    'Peachwood Resort Nainital': 'Nainital',
    'Peachwood Resort Ramgarh': 'Uttarakhand',
    'Penthouse Pattaya': 'Pattaya',
    'Petercat Hotel Sinchon (Hongdae)': 'Seoul',
    'Phan Loft Koh Larn': 'Pattaya',
    'Phoenix Unmatched Comfort - Hotel Near Fateh Sagar Lake Udaipur': 'Udaipur',
    'Phu View Talay Resort': 'Pattaya',
    'Pichcha Kohlarn': 'Pattaya',
    'Pichola Lake Retreat': 'Udaipur',
    'Pichola Vilas': 'Udaipur',
    'Plataran Menjangan Resort and Spa': 'Bali',
    'Pleasant View Resort': 'India',
    'Ploen Place Residence': 'Pattaya',
    'Poinciana Resort Bali': 'Bali',
    'Polo Villa 1 by Avantstay Features Expansive Pool, Spa & Outdoor Firepit 260-322 5 Bedrooms': 'Coachella Valley',
    'Polo Villa 10 by Avantstay Backyard Oasis w/ Putting Green 260320 6 Bedrooms': 'Coachella Valley',
    'Polo Villa 11 by Avantstay Bright Interior w/ Outdoor Bocce Ball, Pool & Spa 260330 5 Bedrooms': 'Coachella Valley',
    "Polo Villa 2 by Avantstay Entertainer's Backyard w/ Pickleball Court, Pool & Spa 260314 6 Bedrooms": 'Coachella Valley',
    'Polo Villa 3 by Avantstay Backyard Retreat w/ Pool, Spa & Firepit 260328 6 Bedrooms': 'Coachella Valley',
    'Polo Villa 5 by Avantstay Outdoor Bocce Ball, Ping Pong Table, Pool & Spa 260332 6 Bedrooms': 'Coachella Valley',
    "Polo Villa 7 by Avantstay Features Entertainer's Backyard + Game Room 260316 5 Bedrooms": 'Coachella Valley',
    'Polo Villa 9 by Avantstay Backyard w/ Putting Green, Pool & Spa 5 BDR 260312': 'Coachella Valley',
    'Pool Access View Laguna Beach Resort 3 Condo': 'Pattaya',
    'Prachuap Beach Hotel': 'Prachuap Khiri Khan',
    'Prachuap Grand Hotel': 'Prachuap Khiri Khan',
    'Prachuap Saam Ao Hotel': 'Prachuap Khiri Khan',
    'Prem Niwas 300-year-old Heritage Boutique Haveli': 'Udaipur',
    'Premier Inn Abergavenny': 'Gales',
    'Premier Inn Monmouth': 'Gales',
    'Premier Inn Oswestry': 'Gales',
    'Pride Hotel Udaipur': 'Udaipur',
    'Prima House Pattaya': 'Pattaya',
    'Prima Sr Hotel & Convention': 'Yogyakarta',
    'ProfilHotels Halmstad Plaza': 'Halmstad',
    'Pullman Chongqing Xiyue': 'Chongqing',
    'Pumphouse Point': 'Australia',
    'Punga Cove Resort': 'Australia',
    'Puri Bali Lovina': 'Bali',
    'Puri Lovina': 'Bali',
    'Puri Mangga Sea View Resort & Spa': 'Bali',
    'Qing Ya Apartment Chongqing': 'Chongqing',
    'Quan Jia Hot Spring B&B': 'Yilan',
    'Quartz Himalayan Brothers': 'India',
    'RAC Margaret River Nature Park': 'Margaret River',
    'ROSASTAYS Jeolikote Bara Bungalow': 'Uttarakhand',
    'RQ North Pattaya By Collection O': 'Pattaya',
    'Raaya Resort Udaipur': 'Udaipur',
    'Radisson Blu Resort Dharamshala': 'Dharamshala',
    'Radisson Chongqing South Hot Spring': 'Chongqing',
    'Radisson Udaipur': 'Udaipur',
    'Raffles Udaipur': 'Udaipur',
    'Rainbow Pines Tourist Caravan Park': 'Australia',
    'Rajdarshan - A Lake View Hotel in Udaipur': 'Udaipur',
    'Ramada Encore by Wyndham Gimpo Han River Hotel': 'Seoul',
    'Ramada Seoul Sindorim Hotel': 'Seoul',
    'Ramada Suites by Wyndham Solo': 'Solo',
    'Ramada by Wyndham Goa Arpora': 'Goa',
    'Ramada by Wyndham La Verkin Zion National Park': 'Zion',
    'Ramada by Wyndham Yogyakarta': 'Yogyakarta',
    'Rambagh Retreat-Stay with  Swimming Pool': 'Udaipur',
    'Ramee Royal Resort & Spa Udaipur': 'Udaipur',
    'Ramee Wolkenburg Resort and Spa Munnar': 'Munnar',
    'Ramgarh Peachwood Resort Nainital': 'Nainital',
    'Ranbanka Hotel & Restaurant': 'India',
    'Rang Noknoy Resort at Koh Larn': 'Pattaya',
    'Rateesumalee pool view KoLarn': 'Pattaya',
    'Rawla Udaipur': 'Udaipur',
    'Red Roof Inn Dillon, SC': 'Red Roof Inn Dillon',
    'RedDoorz Syariah near Jogja City Mall 2': 'Yogyakarta',
    'RedDoorz near Sleman City Hall 2': 'Yogyakarta',
    'RedDoorz near UMY Yogyakarta': 'Yogyakarta',
    'Rediscover Mountain Lodge - Nanshan': 'Chongqing',
    'Reen Resorts Aanavilasam Thekkady': 'Udaipur',
    'Regenta Central Mewargarh Udaipur': 'Udaipur',
    'Regenta Central Udaipur': 'Udaipur',
    'Regina Resort El sokhna': 'Ain Sokhna',
    'Residence Inn by Marriott San Jose North/Silicon Valley': 'San Jose - Silicon Valley',
    'Resort Style Tuscan Living with Spa Pool & Firepit': 'Coachella Valley',
    'Resorts By The Baagh Bhimtal': 'Bhimtal',
    'Retreat Resort Pattaya': 'Pattaya',
    'Richmond Hotel Premier Sendai Ekimae': 'Sendai',
    'Richmond Hotel Sendai': 'Sendai',
    'Rifugio Viote': 'Trento',
    'Rimtalay Resort Koh Larn': 'Pattaya',
    'Rising Shemesh': 'Udaipur',
    'Rising Sun Motor Inn and Cabins - Inside the Park': 'Glacier National Park',
    'River House Bush and Safari Lodge': 'Kruger',
    'RnB Shivani Udaipur': 'Udaipur',
    'Rocky Drift Private Nature Reserve': 'Kruger',
    'Roof Garten Hotel': 'Eskişehir',
    'Room Kohlarn Resort': 'Pattaya',
    'Rosefinch Sarovar Portico Bhimtal': 'Bhimtal',
    'Rosewood Retreat Bhimtal': 'Bhimtal',
    'Rouista Tzoumerka Resort': 'Grecia',
    'Royal Cliff Beach Terrace Hotel Pattaya': 'Pattaya',
    'Royal Palace Hotel Pattaya': 'Pattaya',
    'Royal Prince Resort Pattaya': 'Pattaya',
    'Royal Rafahiya - A Rooftop Lake View Hotel Near Lake Pichola': 'Udaipur',
    'Royal Square Hotel Seoul': 'Seoul',
    'Royal Star Suites Pattaya': 'Pattaya',
    'Ruenthip Residence Pattaya': 'Pattaya',
    'Rumah Gajah by Kubukubali': 'Bali',
    'Rumput Resort & Resto': 'Bali',
    'Ruo Shui Hotspring Hotel': 'Yilan',
    'Ryokan Kazenomori': 'Japan',
    'S Lodge Pattaya (formally known as Sabai Lodge)': 'Pattaya',
    'SPOT ON 92068 Pudja Kesuma Homestay Syariah Yogyakarta': 'Yogyakarta',
    'SPOT ON 93592 Pondok Backpackers Ardafa JogjaNearBlue Lagoon Jogja': 'Yogyakarta',
    'SRINN Hotel Pattaya Klang': 'Pattaya',
    'SSAW Boutique Hotel (Jiefangbei Hongyadong Branch)': 'Chongqing',
    'SUPER HOTEL Premier Sendai Kokubuncho Natural Hot Spring': 'Sendai',
    'SUPER HOTEL Sendai station east Natural Hot Spring': 'Sendai',
    'SYNOSSE PARK HOTEL': 'Istanbul',
    'Sagar Villa Udaipur': 'Udaipur',
    'Sailor Hotel Pattaya': 'Pattaya',
    'Sakura Bed and Breakfast': 'Japan',
    'Sakura Guest House': 'Japan',
    'Samsara Hotel Pattaya': 'Pattaya',
    'Sanco Inn Toyota': 'Toyota',
    'Sarasiruham Resort - Private Pool Villa in Udaipur': 'Udaipur',
    'Sasando Residence Kupang': 'Kupang',
    'Satoria Hotel Yogyakarta': 'Yogyakarta',
    'Savanna Empire Hotel and Resort Spa': 'Kruger',
    'Sayaji Resort and Spa Udaipur': 'Udaipur',
    'Scenic, Munnar - IHCL SeleQtions': 'Munnar',
    'Schlosshotel Marienbad': 'Marienbad',
    'Sea Breeze Lodge Ngapali': 'Ngapali Beach',
    'Sea Crest By Jomtien': 'Pattaya',
    'Sea Inn Pattaya': 'Pattaya',
    'Sea Me Spring Tree Hotel - Adults only': 'Pattaya',
    'Sealey Resort Koh Larn': 'Pattaya',
    'Season Five Hotel': 'Pattaya',
    'Seasons Boutique Hotel near Sajjangarh Biological Park, Udaipur': 'Udaipur',
    'Seclude Ramgarh Willows': 'Uttarakhand',
    'Seehotel am Tankumsee': 'Wolfsburg',
    'Selina Place Pattaya': 'Pattaya',
    'Sendai Kokusai Hotel': 'Sendai',
    'Serenity Condo Wongamat by Patsamon': 'Pattaya',
    'Serenity Hill Resort Near - 2Km Fateh Sagar Lake Udaipur': 'Udaipur',
    'Serkong House': 'Dharamshala',
    'Seven Fukun Hotel': 'Taiwan',
    'Shafei Hotel Chongqing Dadukou': 'Chongqing',
    'Shagwell Mansions Pattaya': 'Pattaya',
    'Shambhala Hotel Pattaya': 'Pattaya',
    'Shamrock Hotel Pattaya': 'Pattaya',
    'Shandori Hotel': 'Yilan',
    'Shankara Munduk Bali': 'Bali',
    'Shankou Hotspring Hotel': 'Yilan',
    'Sherwood View Accommodation': 'Australia',
    'Shilla Stay Guro': 'Seoul',
    'Shilla Stay Mapo': 'Seoul',
    'Shilla Stay Seocho Gangnam Station': 'Seoul',
    'Shisuikaku Toufuya': 'Toyota',
    'Shree Ji Mahal Hotel': 'Udaipur',
    'Silks Place Yilan': 'Yilan',
    'Silver Oasis Maldives': 'Maldivas',
    'Sinclairs Palace Retreat Udaipur': 'Udaipur',
    'Sinclairs Udaipur': 'Udaipur',
    'Singwe Private Safari lodge': 'Kruger',
    'Sita Royal Lakside Chalet': 'Udaipur',
    'Six Fukun Hotel': 'Taiwan',
    'Six Senses Shaharut': 'Israel',
    'Sky hip resort jomtean pattaya': 'Pattaya',
    'Skyline Cafe And Stay Gagar': 'Uttarakhand',
    'Sleep With Me Pattaya': 'Pattaya',
    'Slow Wow Hot Spring Hotel': 'Yilan',
    'Smart Place Pattaya': 'Pattaya',
    'Smile Hotel Otsu Seta': 'Otsu',
    'Smile Hotel Sendai Kokubuncho': 'Sendai',
    'Sofitel Inle Lake Myat Min Hotel': 'Inle Lake',
    'Soham Haveli Udaipur': 'Udaipur',
    'Soi 2 inn Pattaya': 'Pattaya',
    'Soi 5 Apartment': 'Pattaya',
    'Sojourn with Nyoli': 'Dharamshala',
    'Solares Cumbrecita': 'Cumbrecita',
    'Sotetsu Fresa Inn Sendai': 'Sendai',
    'Sotis Hotel Kupang': 'Kupang',
    'Spacious 2 BR at Water Side El Gouna': 'El Gouna',
    'Spectrum Resort & Spa, Udaipur': 'Udaipur',
    'Sporthotel Malchow': 'Mecklenburg',
    'Spring Sky Udaipur by ShriGo Hotels': 'Udaipur',
    'Stadthotel Engel': 'Ettlingen',
    'Star Hotel Pattaya': 'Pattaya',
    'Star Shine B&B': 'Yilan',
    'Stay Hotel Gangnam': 'Seoul',
    'Stay Inn Hotel - Ain Sokhna': 'Ain Sokhna',
    'Stay Resort Pattaya': 'Pattaya',
    'Staybridge Suites Eastvale Norco by IHG': 'Los Angeles (and vicinity), CA, US',
    'Sterling Aravalli Udaipur': 'Udaipur',
    'Sterling Balicha Udaipur': 'Udaipur',
    'Sterling Jaisinghgarh Udaipur': 'Udaipur',
    'Stone Wood Beach Resort': 'Goa',
    'Storica Stays Panorama Haveli Udaipur': 'Udaipur',
    'Storii By ITC Hotels Amoha Retreat, Dharamshala': 'Dharamshala',
    'Studtmanns Gasthof': 'Saxen',
    'Sucha Hotel Chongqing Danzishi Laojie': 'Chongqing',
    'Sucha Hotel Chongqing North Station': 'Chongqing',
    'Sucha Hotel Chongqing Yangjiaping': 'Chongqing',
    'Sukkeebeach Kohlarn Resort': 'Pattaya',
    'Sun Suko Boutique Retreat': 'Bali',
    'Sun and Sea Kohlarn': 'Pattaya',
    'Suncity Hotel Pattaya': 'Pattaya',
    'Sunday Chateau En Ville Pattaya': 'Pattaya',
    'Sunday Grand Jomtien Pattaya': 'Pattaya',
    'Sundown Country Estate': 'Sudáfrica',
    'Sunshine Coast Inn': 'Pattaya',
    'Sunshine Hip Hotel': 'Pattaya',
    'SunshineZone': 'Pattaya',
    'Super 8 by Wyndham Cut Bank': 'Cut Bank',
    'SureStay Plus by Best Western T Pattaya': 'Pattaya',
    'Sureena Hotel': 'Pattaya',
    'Surya Kothi Resort': 'Udaipur',
    'Sutus Court 1': 'Pattaya',
    'Sutus Court 2': 'Pattaya',
    'Sutus Court 3': 'Pattaya',
    'Sutus Court 4': 'Pattaya',
    'Sutus Court 5': 'Pattaya',
    'Sutus Court 7': 'Pattaya',
    'Swantown Inn': 'Olympia',
    'Swiftcurrent Motor Inn and Cabins - Inside the Park': 'Glacier National Park',
    'Swiss-Belcourt Kupang': 'Kupang',
    'T2 Jomtien Pattaya': 'Pattaya',
    'TFT Chongqing, Vignette Collection by IHG': 'Chongqing',
    'THE JJ CORBETT BLISS': 'Jim Corbett',
    'THE MUSTEL HOTEL CHONGQING. HONGYADONG': 'Chongqing',
    'TOLIP Resort El Galala Majestic': 'Ain Sokhna',
    'TSix5 Quarter': 'Pattaya',
    'Tabist Shizukuishi Resort Hotel': 'Shizukuishi',
    'Taj Aravali Resort & Spa': 'Udaipur',
    'Tawaen Beach Resort': 'Pattaya',
    'Tawaen Caza Sky Camping': 'Pattaya',
    'Taşlıhan Boutique Hotel': 'Istanbul',
    'Teluk Karang Dive and Spa Resort Bali': 'Bali',
    'Tenlien onsen Hot Spring Hotel': 'Japan',
    'Thai Pura Resort': 'Pattaya',
    'The  Seathru  Kohlarn': 'Pattaya',
    'The AGATE Pattaya Boutique Resort': 'Pattaya',
    'The Amargarh': 'Udaipur',
    'The Atrium Hotel and Resort Yogyakarta': 'Yogyakarta',
    'The Basil Hotel': 'Udaipur',
    'The Beach Front Resort Pattaya  - SHA Plus': 'Pattaya',
    'The Biletha Bagh': 'Udaipur',
    'The Cabin Hotel Lovina Bali': 'Bali',
    'The Cangkringan Jogja Villas & Spa': 'Yogyakarta',
    'The Castle Villa Udaipur': 'Udaipur',
    'The ChanThong Hotel Pattaya': 'Pattaya',
    'The Chronicles by WSI - Near the Lake Pichola Udaipur': 'Udaipur',
    'The Classic Crown Udaipur - A Luxury Hotel by Lake Pichola': 'Udaipur',
    'The Cloud by PSR': 'Pattaya',
    'The ClubHouse Residence by PSR': 'Pattaya',
    'The Corner Lodge': 'Pattaya',
    'The Cozy Acorn Resort': 'Mukteshwar',
    'The Crescent Udaipur | Boutique Hotel Near Lake Pichola': 'Udaipur',
    'The Designers LYJ Gangnam Premier': 'Seoul',
    'The Divine Hills Resort Udaipur': 'Udaipur',
    'The ESSE Hotel Pattaya': 'Pattaya',
    'The Elysium Pratumnak Pattaya - By SHG': 'Pattaya',
    'The Fern Bambora Fort Udaipur, Bambora, Series by Marriott': 'Udaipur',
    'The Fern Hillside Resort Bhimtal': 'Bhimtal',
    'The Fern Residency Bhuj': 'Bhuj',
    'The Fern Residency Udaipur, Series by Marriott': 'Udaipur',
    'The Gems Mining Pool Villas Pattaya': 'Pattaya',
    'The Gran Resort Ohmimaiko': 'Otsu',
    'The Grand Fateh': 'Udaipur',
    'The Grand Lodge Pattaya': 'Pattaya',
    'The Grand Uddhav Hotel': 'Udaipur',
    'The Grass Serviced Suites by At Mind': 'Pattaya',
    'The Heritage Pattaya Beachfront Resort': 'Pattaya',
    'The Heron House': 'Maine',
    'The Hideaway Resort Pattaya Chonburi': 'Pattaya',
    'The Himalayan Living - Whispering Oaks': 'India',
    'The Himalayan Living Whistling Pines': 'India',
    'The Himalayan Odyssey and Cottages': 'India',
    'The Hoften Snowia Luxury Stay Near Bhalugarh Waterfall': 'Mukteshwar',
    'The Hotel Route-Inn Sendai Higashi': 'Sendai',
    'The Jagat Hotel and Spa Udaipur': 'Udaipur',
    'The KN Kohlarn': 'Pattaya',
    'The Kirana Tembok': 'Bali',
    'The LD Pattaya': 'Pattaya',
    'The Lake Heritage @Bhimtal Lake': 'Bhimtal',
    'The Lake View Hotel – On Lake Pichola': 'Udaipur',
    'The Leela Palace Udaipur': 'Udaipur',
    'The Light House Resort - Kohlarn': 'Pattaya',
    'The Local Menjangan': 'Bali',
    'The Lodge Jomtien 7': 'Pattaya',
    'The Lodge Jomtien 9': 'Pattaya',
    'The Lodge Pattaya': 'Pattaya',
    'The Manja Retreat Lovina Bali': 'Bali',
    'The Moment Hotel Yilan by Lakeshore': 'Yilan',
    'The Montail Udaipur': 'Udaipur',
    'The Monttra Pattaya': 'Pattaya',
    'The Mukteshwar Inn Rooftop Cafe': 'Mukteshwar',
    "The Nature's Green Resort -Bhimtal": 'Bhimtal',
    'The O Villa Jiaoxi': 'Yilan',
    'The Omala Resort Tretes': 'Surabaya',
    'The One Sabai Living': 'Pattaya',
    'The OneFive Sendai': 'Sendai',
    'The Paradise Bliss - A Luxury Hotel & Spa in Udaipur': 'Udaipur',
    'The Park Classic Udaipur': 'Udaipur',
    'The Park Pattaya': 'Pattaya',
    'The Peak Towers by PSR': 'Pattaya',
    'The Pluck Umagarh': 'Mukteshwar',
    'The Proud Hotel Pattaya': 'Pattaya',
    'The Quba Boutique Hotel Pattaya': 'Pattaya',
    'The Ramvilas - A Rooftop Lake View Hotel in Udaipur': 'Udaipur',
    'The Rangers reserve Jim Corbett': 'Jim Corbett',
    'The Riviera Wongamat by Pattaya Holiday': 'Pattaya',
    'The Rizin Hotel Phratumnak': 'Pattaya',
    'The Royal Adobe Pattaya': 'Pattaya',
    'The Sala Pattaya': 'Pattaya',
    'The Sanctuary Resort Pattaya, BW Signature Collection': 'Pattaya',
    'The Sky Imperial Udaipur': 'Udaipur',
    'The Sloop Inn': 'Cornwall',
    'The Tamnan Pattaya Hotel & Resort': 'Pattaya',
    'The Train Resort': 'Pattaya',
    'The Udaipur Luxurious Villa Udaipur': 'Udaipur',
    'The Unmad': 'Dharamshala',
    'The Unmad Satovari': 'Dharamshala',
    'The Vaag Udaipur A Luxury Pool Villa in Udaipur': 'Udaipur',
    'The Village at River Landing Cottages': 'Wallace',
    'The Westin Yilan Resort': 'Yilan',
    'The Westlake Hotel & Resort Yogyakarta': 'Yogyakarta',
    'The Windy Mist Resort Munnar': 'Munnar',
    'The Wonderland B&B': 'Yilan',
    'The Zen Hotel Pattaya': 'Pattaya',
    'The Zign Hotel': 'Pattaya',
    'The central lovina hotel & restaurant': 'Bali',
    'The haveli lounge and restaurant': 'Udaipur',
    'Thorn Hill Vineyard Villas': 'Temecula',
    'Ti amo Kohlarn': 'Pattaya',
    'Tian Long Hotel': 'Yilan',
    'Tianya Wuxi river Hotel': 'Chongqing',
    'Tiny Home Resorts': 'USA',
    'Tiny Home Vacations Resort': 'USA',
    'Tirta Sari Bungalows & Spa': 'Bali',
    'Tojinbo Mikuni Onsen Ootoku': 'Japan',
    'Tolip Resort Elgalala Hills': 'Aswan',
    'Toonja kohlarn': 'Pattaya',
    'Tourist Settlement Brzet': 'Croacia',
    'Towneplace Suites By Marriott Toledo Perrysburg': 'Toledo',
    'Toyoko Inn Kyoto Biwako Otsu': 'Kyoto',
    'Toyoko Inn Sendai Higashi 2': 'Sendai',
    'Toyoko Inn Sendai Higashi-guchi No.1': 'Sendai',
    'Toyoko Inn Sendai Nishi Hirose Dori': 'Sendai',
    'Toyoko Inn Seoul Gangnam': 'Seoul',
    'Toyoko Inn Toyota-shi Ekimae': 'Toyota',
    'Toyota Prestige Hotel': 'Toyota',
    'Trang blue hotel': 'Trang',
    'Tree of Life Amara Resorts & Spa Udaipur': 'Udaipur',
    'Treebo The Fresco Lake Pichola': 'Udaipur',
    'Treebo The Regal House, Near Fateh Sagar Lake': 'Udaipur',
    'Treetops Condominium by PSR': 'Pattaya',
    'Tri-Shawa Resort': 'Pattaya',
    'Tribe Pattaya': 'Pattaya',
    'Trijaya Guest House': 'Bali',
    'Tripletree Sinergi Hotel Tretes': 'Surabaya',
    'Tsix5 Phenomenal Hotel Pattaya': 'Pattaya',
    'Turban Roopgarh Resort and Spa, Udaipur': 'Udaipur',
    'Two Chimney, Gethia, Nainital': 'Nainital',
    'Tycoon Suite Pattaya': 'Pattaya',
    'Udai Nature Valley Resort Udaipur': 'Udaipur',
    'Uddhav Vilas': 'Varanasi',
    'Unique Regency Pattaya': 'Pattaya',
    'Ushaan Haveli': 'Udaipur',
    'V Style Pattaya North Beach': 'Pattaya',
    'VR-Ain Sokhna Chalet': 'Ain Sokhna',
    'VR-Ajilika': 'Aswan',
    'VR-Alhayat Ain El Sokhna': 'Ain Sokhna',
    'VR-Apartment Overlooking Pool & Lagoon': 'El Gouna',
    'VR-Blue Bay Asia Resort El Sokhna': 'Ain Sokhna',
    'VR-Buena Vista by Avantstay Massive Outdoor Oasis w/ Pool, Spa & Firepit!': 'Coachella Valley',
    'VR-Casa Serenity Luxury Living w/ Pool & Jacuzzi': 'Coachella Valley',
    'VR-Casa del Arbol by Avantstay Stunning California Estate With Incredible Views': 'Temecula',
    'VR-Chalet In Belagio Ain Sokhna': 'Ain Sokhna',
    'VR-Charming Villa in El Gouna with Pool': 'El Gouna',
    'VR-Chestnuthill Countryside Manor': 'Pocono Mountains',
    'VR-Cloud9 Coachella': 'Coachella Valley',
    'VR-Colina by Avantstay Secluded Mountain Top Oasis w/ Pool, Hot Tub & Putting Green!': 'Coachella Valley',
    'VR-Costa Bella Condominiun Resort': 'Philippines',
    'VR-De Luz by Avantstay 5 Acre Estate w/ Lake, Pool & Hot Tub': 'Temecula',
    'VR-Eagle River Vacation Home': 'Eagle River',
    'VR-El Gouna Rental Smokery Beach Apartment': 'El Gouna',
    'VR-El Reino by Avantstay Spectacular Estate w/ Pool & Tennis Court!': 'Temecula',
    'VR-Extremely Private Villa With Optional Pool Heating': 'El Gouna',
    'VR-Fadlos Anay Nubian Guesthouse': 'Aswan',
    'VR-Feel Above it All in Utah!': 'Utah',
    'VR-Global Luxury Suites Sunnyvale North': 'San Jose - Silicon Valley',
    'VR-Indian Palms Oasis - Just a Walk to Festivals!': 'Coachella Valley',
    'VR-Ken Ken Villa Yuumodoro': 'Okinawa',
    'VR-Kite & Beach Apartment in Mangroovy': 'El Gouna',
    'VR-La Barrique by Avantstay Secluded 14 Acre Estate w/ Vball & Pool': 'Coachella Valley',
    'VR-Lagoon Villa in El Gouna': 'El Gouna',
    'VR-Lakeside in the Desert': 'Coachella Valley',
    'VR-Losari Retreat': 'Yogyakarta',
    'VR-Luxurious Villa Living in Indio w/ Pool/Spa': 'Coachella Valley',
    'VR-Mandala Springs Wellness Retreat Center': 'Cobb',
    'VR-Marilyn by Avantstay Mins to Old Town La Qunita!': 'Coachella Valley',
    'VR-Merlot by Avantstay Exquisite Home w/ Pool and Stunning Patio': 'Coachella Valley',
    'VR-Nile Cruise 3 or 4 or 7 nights': 'Aswan',
    'VR-Paraiso de Motobu': 'Okinawa',
    'VR-Saltwater Suites': 'Maine',
    'VR-Stunning Golf Villa in El Gouna': 'El Gouna',
    'VR-Sunset Hideaway Near National Parks & Hike/bike': 'Zion',
    'VR-Sweet Retreat Rest & Relax Near National Parks': 'Zion',
    'VR-The Berri Bubble Lodge': 'Australia',
    'VR-The Pool & Sauna Villa MOTOBU': 'Okinawa',
    'VR-The Riesling Retreat by Avantstay Estate w/ Pool, Hottub, Putting Green & Pickle Ball Court!': 'Coachella Valley',
    'VR-The Village at RiverLanding': 'Wallace',
    'VR-VESTA - El Gouna Residence': 'El Gouna',
    'VR-Vesta - Luxury APT - 2BR - Rihana': 'El Gouna',
    'VR-Vesta - Superior Villa - 3 BR - North Golf': 'El Gouna',
    'VR-Warhol by Avantstay Expansive Estate Stunning Wine Cty Views': 'Coachella Valley',
    'VR-Whitefish Stage Hideaway': 'Whitefish',
    'VS Beach Front Pattaya': 'Pattaya',
    'Vaibhavya Hotel and Restaurant-Udaipur': 'Udaipur',
    'Valhalla Pattaya Hotel': 'Pattaya',
    'Vanko International Hotel Pattaya': 'Pattaya',
    'Vasty Hotel': 'Yilan',
    'Veranda Resort Pattaya - MGallery Collection': 'Pattaya',
    'Veronica Resort , BY THE  BEACH': 'Goa',
    'Vesta - Luxury Villa - 4 BR - Nubia': 'Aswan',
    'Vesta Grand Central Udaipur': 'Udaipur',
    'Vibe Munnar Resort & Spa': 'Munnar',
    'View Lodge Biwa': 'Otsu',
    'Vijaygarh Resort & Cottages with Private Pool': 'India',
    'Villa Inn Udaipur by Yansh Group': 'Udaipur',
    'Villa Inn-Adult Only- Temecula Wine Country': 'Temecula',
    'Villa Lamai - Wong Amat House Pattaya': 'Pattaya',
    'Villa Le Palm - Luxury Resort Near Fateh Sagar Lake (3 KM) Udaipur': 'Udaipur',
    'Villa Mayurana By Edwards Collection': 'Galle',
    'Villa Misk': 'Arabia Saudita',
    'Villa Oranje Pattaya': 'Pattaya',
    'Villa Vilas': 'Udaipur',
    'Villas del Malbec Lodge': 'Mendoza',
    'Vinsober Kainchi Dham Nainital': 'Nainital',
    'Virawan pool resort kohlarn': 'Pattaya',
    'Vista Hotel Naini Lake View Nainital': 'Nainital',
    'Vista Valley Stay - Dharamshala': 'Dharamshala',
    'Vivir Jiaoxi Hotel': 'Yilan',
    'Voco Seoul Gangnam': 'Seoul',
    'Vyluk Hotel Chongqing Airport': 'Chongqing',
    'Vyluk J Hotel Chongqing Jiefangbei': 'Chongqing',
    'W14 Pattaya': 'Pattaya',
    'W1A Jomtien': 'Pattaya',
    'Walking Street Residence - Boutique Suites': 'Pattaya',
    'Wan DD Resort Kohlarn': 'Pattaya',
    'Wanda Amber Chongqing': 'Chongqing',
    'Wanda Encore Chongqing': 'Chongqing',
    'Wanderlust Mukteshwar': 'Mukteshwar',
    'Wapnö Gårdshotell': 'Halmstad',
    'Washington R&B Hotel Sendai Higashiguchi': 'Sendai',
    'Water Park by PSR ASIA': 'Pattaya',
    'Waterbirds Family': 'Yilan',
    'Wei Wei Chu B&B': 'Yilan',
    'WelcomHeritage Natraj McLeod Ganj': 'Dharamshala',
    'Welcome Jomtien Beach Hotel': 'Pattaya',
    'Wellspring by Silks Jiao Xi': 'Yilan',
    'Welnez World Residence Pattaya': 'Pattaya',
    'Whitehouse Condotel': 'Pattaya',
    'Willamette Pass Inn Chalets': 'Oregon',
    'Windale Resorts Munnar': 'Munnar',
    'Wisma Joyo': 'Yogyakarta',
    'Wisma Lee A Lee': 'Yogyakarta',
    'Woodspring Suites Corona': 'Los Angeles (and vicinity), CA, US',
    'Wudai Homestay': 'Yilan',
    'Wyatt Hotel Jomtien Beach': 'Pattaya',
    'Wyndham Garden Yogyakarta': 'Yogyakarta',
    'Wyndham Grand Nai Harn Beach Phuket': 'Phuket',
    'Wyndham Jomtien Pattaya': 'Pattaya',
    'X Hotel Pattaya': 'Pattaya',
    'XQ Pattaya Hotel': 'Pattaya',
    'Xenious Micro Villas Goa': 'Goa',
    'Xian Hotel': "Xi'an",
    'XiannvshanHuabang': 'Chongqing',
    'Xinchuan Homestay': 'Taiwan',
    'Xingyao Vista Hotel - Jiefangbei Area Hong Ya Dong': 'Chongqing',
    'Xingzhi Yunbo Riverview Hotel (Chongqing Jiefangbei Hongyadong Branch)': 'Chongqing',
    "Y's house in Hongdae": 'Seoul',
    'YA-NOLD Hot Spring Hotel': 'Yilan',
    'YAAN Udaipur': 'Udaipur',
    'YZ Spa house': 'Yilan',
    'Yamagata Kaku Hotel & Spa': 'Yilan',
    'Yapo Bed & Breakfast': 'Luodong',
    'Yeouido Park Centre, Marriott Executive Apartments': 'Seoul',
    'Yilan Feeling Homestay B&B': 'Yilan',
    'Yilan Greenbird of Happiness B&B': 'Yilan',
    'Yilan Jimmy Villa': 'Yilan',
    'Yilan Siao Jhu': 'Yilan',
    'Yilan Xiang Feng Homestay': 'Yilan',
    'Yogyakarta Marriott Hotel': 'Yogyakarta',
    'Yu Peng Villa': 'Taiwan',
    'Yueyin Chongqing Courtyard': 'Chongqing',
    'Yulan Hakodate': 'Japan',
    'Yumoto Hotel Achikawa': 'Tokyo',
    'Yunohara Hotel': 'Sendai',
    'Yupan Yunge Homestay - Jiefangbei Store': 'Chongqing',
    'ZIP Hotel': 'Seoul',
    'Zana Lake Resort Udaipur': 'Udaipur',
    'Zen Ocean B&B': 'Yilan',
    'Zhen Shan Zhuang B&B': 'Yilan',
    'Zion White Bison': 'Zion',
    'Zubani hotel and suites': 'Enugu',
    'blackwoods Hotel Pattaya': 'Pattaya',
    'bloomrooms @ Calangute': 'Goa',
    'chongqingyinshiguangjiangjingjiudian': 'Chongqing',
    'elephant memories safari lodge': 'Kruger',
    'ibis Styles Athens Routes': 'Athens',
    'janak vilas': 'Udaipur',
    'juSTa Luxe Sajjangarh Resort & Spa, Udaipur': 'Udaipur',
    'juSTa Mukteshwar Retreat & Spa': 'Mukteshwar',
    'lebua Udaipur Daulatgarh': 'Udaipur',
    'samastiti lovina': 'Bali',
    'steinhorst hotel': 'Wolfsburg',
    '重庆暖余江景民宿 Chongqing Nuanyu River View Hotel': 'Chongqing',
}
